# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.ts from the
# native-release-manifest.json published with v0.1.1. Do not hand-edit the
# version/url/sha256 fields below -- rerun the script against a release
# manifest instead. See homebrew/README.md for how this formula is used until
# it moves to a dedicated tap repository.
class Amfaa < Formula
  desc "Multi-agent chatroom for coding with AI models (native app)"
  homepage "https://github.com/virusimmortal00/AllMyFriendsAreAgents"
  license "MIT"
  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/virusimmortal00/AllMyFriendsAreAgents/releases/download/v0.1.1/all-my-friends-are-agents-v0.1.1-darwin-arm64.tar.gz"
      sha256 "13217107633c787cf3519e0dabc0b73e467ab607852374fd8c77c195649d7e56"
    end

    on_intel do
      url "https://github.com/virusimmortal00/AllMyFriendsAreAgents/releases/download/v0.1.1/all-my-friends-are-agents-v0.1.1-darwin-x64.tar.gz"
      sha256 "5e51dd94e8531b25515dbc0a412c52b4078e36b94c798e8c23751b360cca153e"
    end
  end

  def install
    # The published archive is a fully self-contained bundle: it ships its
    # own pinned Node.js runtime and the audited OpenCode runtime, so no
    # other dependency is declared here. Its "amfaa" launcher locates the
    # sibling active-version/versions/ directories relative to its own real
    # path (see scripts/install-native.sh), so it must keep living in
    # libexec -- write an exec wrapper into bin rather than a symlink.
    libexec.install Dir["*"]
    bin.write_exec_script libexec/"amfaa"
  end

  test do
    identity = JSON.parse(shell_output("#{bin}/amfaa version"))
    assert_equal version.to_s, identity.fetch("application").fetch("version")
  end
end
