import type express from "express";
import { isActiveAgentId } from "../shared/participants.js";
import { commandHelpText, type CommandInput } from "../shared/command-domain.js";
import { commandPollCursor, publicPollProjection, type CommandRecordStore } from "./command-record.js";
import type { CommandRuntime, CommandResponse } from "./command-runtime.js";
import type { DeveloperTeamRegistry } from "./developer-team.js";
import type { ControlPlaneStore } from "./control-plane.js";
import type { HumanPresenceRegistry } from "./human-presence.js";
import { sessionHuman, type HumanSessions } from "./human-session.js";
import { CANONICAL_ROOM_ID } from "./storage/room-repository.js";

function statusFor(result: CommandResponse) { return result.kind === "private-error" ? 400 : result.kind === "private-help" ? 200 : result.duplicate ? 200 : 202; }
export function sendCommandResponse(response: express.Response, result: CommandResponse, clientSubmissionId?:string) { return response.status(statusFor(result)).set("Cache-Control","no-store").json(clientSubmissionId ? { command:true, clientSubmissionId, result } : result.kind === "private-error" ? { error:result.message,kind:result.kind } : result); }

export async function submitHumanCommand(input:{request:express.Request;response:express.Response;runtime:CommandRuntime;store:CommandRecordStore & Pick<import("./storage/room-repository.js").RoomRepository,"addPrivateCommandResponseOnce">;humans:HumanPresenceRegistry;sessions:HumanSessions;text?:string;broadcast?:()=>void;humanIsMember?:(humanId:string)=>boolean}) {
  const human=sessionHuman(input.request,input.humans,input.sessions); if(!human)return input.response.status(401).json({error:"Join the room before running commands."});
  if(input.humanIsMember&&!input.humanIsMember(human.id))return input.response.status(403).set("Cache-Control","no-store").json({error:"Room membership is required before running commands.",kind:"private-error"});
  const command=(input.text??input.request.body?.text) as CommandInput; const suppliedId=input.request.body?.clientSubmissionId??input.request.body?.clientMessageId;const clientSubmissionId=typeof suppliedId==="string"?suppliedId.trim():"";
  const result=await input.runtime.submit(command,{kind:"human",id:human.id,displayName:human.name},clientSubmissionId);
  if(result.kind==="private-help") { await input.store.addPrivateCommandResponseOnce(result.submissionId,human.id,commandHelpText(result.commands)); input.broadcast?.(); }
  return sendCommandResponse(input.response,result,clientSubmissionId);
}

export function registerCommandRoutes(input:{app:express.Express;runtime:CommandRuntime;store:CommandRecordStore & Pick<import("./storage/room-repository.js").RoomRepository,"addPrivateCommandResponseOnce">;humans:HumanPresenceRegistry;sessions:HumanSessions;developers:DeveloperTeamRegistry;control?:ControlPlaneStore;broadcast?:()=>void;humanIsMember?:(humanId:string)=>boolean}) {
  const {app,runtime,store,humans,sessions,developers}=input;
  const controller=(request:express.Request,csrf=false)=>{try{const session=input.control?.require(request,"ROSTER_MANAGE",csrf);return session?{kind:"controller" as const,id:session.principal.id,displayName:session.principal.username}:undefined;}catch{return undefined;}};
  const canReadDiagnostics=(authorization:string|undefined)=>developers.authenticate(authorization,"DIAGNOSTIC_READ");
  app.post("/api/commands",(request,response)=>submitHumanCommand({request,response,runtime,store,humans,sessions,broadcast:input.broadcast,humanIsMember:input.humanIsMember}));
  app.get("/api/commands/:submissionId/github-diagnostic",async(request,response)=>{const human=sessionHuman(request,humans,sessions);if(!human)return response.status(401).json({error:"Join the room before viewing diagnostics."});const result=await runtime.getGhDiagnostic({kind:"human",id:human.id,displayName:human.name},String(request.params.submissionId));return response.status(result.kind==="private-error"?404:200).set("Cache-Control","no-store").json(result);});
  app.post("/api/developer/commands",async(request,response)=>{const authenticated=developers.authenticate(request.header("authorization"),"COMMAND_RUN");if(!authenticated)return response.status(404).json({error:"Not found."});if(!isActiveAgentId(authenticated.member.memberId))return response.status(403).json({error:"The authenticated member is not a room agent."});const clientSubmissionId=typeof request.body?.clientSubmissionId==="string"?request.body.clientSubmissionId.trim():"";return sendCommandResponse(response,await runtime.submit(request.body?.invocation as CommandInput,{kind:"agent",id:authenticated.member.memberId,displayName:authenticated.member.displayName},clientSubmissionId),clientSubmissionId);});
  app.post("/api/polls/:pollId/votes",async(request,response)=>{const human=sessionHuman(request,humans,sessions);if(!human)return response.status(401).json({error:"Join the room before voting."});const result=await runtime.vote(String(request.params.pollId),{kind:"human",id:human.id,displayName:human.name},String(request.body?.clientVoteId||""),request.body?.optionIndex);return response.status(result.kind==="accepted"?result.duplicate?200:201:400).set("Cache-Control","no-store").json(result);});
  app.post("/api/polls/:pollId/close",async(request,response)=>{const human=sessionHuman(request,humans,sessions);if(!human)return response.status(401).json({error:"Join the room before ending a poll."});const poll=await store.getCommandPoll(CANONICAL_ROOM_ID,String(request.params.pollId));if(!poll)return response.status(404).json({error:"Poll not found."});const invoker=poll.creatorKind==="human"&&poll.creatorId===human.id?{kind:"human" as const,id:human.id,displayName:human.name}:controller(request,true);if(!invoker)return response.status(403).json({error:"Only the poll creator or a room controller can end this poll."});const result=await runtime.closePoll(poll.pollId,invoker,String(request.body?.clientCloseId||""),request.body?.expectedRevision);return response.status(result.kind==="accepted"?result.duplicate?200:201:400).set("Cache-Control","no-store").json(result);});
  app.get("/api/polls",async(request,response)=>{const human=sessionHuman(request,humans,sessions);if(!human)return response.status(401).json({error:"Join the room before viewing polls."});const canControl=Boolean(controller(request));const requestedLimit=Number(request.query.limit||20);const limit=Number.isFinite(requestedLimit)?Math.max(1,Math.min(50,Math.floor(requestedLimit))):20;const before=typeof request.query.before==="string"?request.query.before:undefined;const polls=await store.listCommandPolls(CANONICAL_ROOM_ID,{limit:limit+1,before,state:"OPEN"});const page=polls.slice(0,limit);const items=await Promise.all(page.map(async(poll)=>publicPollProjection(poll,await store.listCommandVotes(CANONICAL_ROOM_ID,poll.pollId),{kind:"human",id:human.id,canControl})));const boundary=page.at(-1);return response.set("Cache-Control","no-store").json({items,nextCursor:polls.length>limit&&boundary?commandPollCursor(boundary):null});});
  app.get("/api/polls/:pollId",async(request,response)=>{const human=sessionHuman(request,humans,sessions);if(!human)return response.status(401).json({error:"Join the room before viewing polls."});const poll=await store.getCommandPoll(CANONICAL_ROOM_ID,String(request.params.pollId));if(!poll)return response.status(404).json({error:"Poll not found."});return response.set("Cache-Control","no-store").json(publicPollProjection(poll,await store.listCommandVotes(CANONICAL_ROOM_ID,poll.pollId),{kind:"human",id:human.id,canControl:Boolean(controller(request))}));});
  app.get("/api/developer/diagnostics",async(request,response)=>{if(!canReadDiagnostics(request.header("authorization")))return response.status(404).json({error:"Not found."});const agentId=typeof request.query.agentId==="string"&&isActiveAgentId(request.query.agentId)?request.query.agentId:null;if(!agentId)return response.status(400).json({error:"A valid room agent scope is required."});const search=typeof request.query.search==="string"?request.query.search:undefined;if(search&&search.length>200)return response.status(400).json({error:"Diagnostic search is limited to 200 characters."});const reason=typeof request.query.reason==="string"?request.query.reason.slice(0,80):undefined;const requestedLimit=Number(request.query.limit||50);const limit=Number.isFinite(requestedLimit)?Math.max(1,Math.min(50,Math.floor(requestedLimit))):50;return response.set("Cache-Control","no-store").json({items:await store.listDiagnostics(CANONICAL_ROOM_ID,{agentId,search,reason,limit})});});
  app.get("/api/developer/diagnostics/:recordId",async(request,response)=>{if(!canReadDiagnostics(request.header("authorization")))return response.status(404).json({error:"Not found."});const agentId=typeof request.query.agentId==="string"&&isActiveAgentId(request.query.agentId)?request.query.agentId:null;if(!agentId)return response.status(400).json({error:"A valid room agent scope is required."});const record=await store.getDiagnostic(CANONICAL_ROOM_ID,agentId,String(request.params.recordId));return record?response.set("Cache-Control","no-store").json(record):response.status(404).json({error:"Diagnostic record not found."});});
}
