import {createHash} from "node:crypto";import {afterEach,describe,expect,it,vi} from "vitest";import {mkdtemp,rm} from "node:fs/promises";import os from "node:os";import path from "node:path";import {RoomStore} from "./room-store.js";import {CommandRuntime} from "./command-runtime.js";import {GitHubReadAdapter,GitHubReadFailure,type GitHubReadFetch} from "./github-read-adapter.js";import {GitHubReadStore} from "./github-read-store.js";import {GitHubReadService,type GitHubReadCommandService} from "./github-read-service.js";import {COMMAND_CATALOG_REVISION,ROOM_COMMANDS} from "../shared/command-domain.js";import {legacyDefaultRoomAgentRoster} from "../shared/roster.js";import {CANONICAL_ROOM_ID} from "./storage/room-repository.js";
const roots:string[]=[];const runtimes:CommandRuntime[]=[];afterEach(async()=>{await Promise.all(runtimes.splice(0).map((r)=>r.close()));await Promise.all(roots.splice(0).map((r)=>rm(r,{recursive:true,force:true})));});const sha="0123456789abcdef0123456789abcdef01234567";
async function fixture(fetcher:GitHubReadFetch,existing?:{root:string;store:RoomStore},failPublication=false,githubRead?:GitHubReadCommandService){const root=existing?.root||await mkdtemp(path.join(os.tmpdir(),"amfaa-gh-runtime-"));if(!existing)roots.push(root);const store=existing?.store||await RoomStore.open(root,path.join(root,"state"));const entries=store.snapshot().roster!.entries;const roster=(entries.length?entries:legacyDefaultRoomAgentRoster().entries).map((entry)=>entry.agentId==="codex-sol"?{...entry,commandPermissions:{allowAll:false,allowed:[...ROOM_COMMANDS],catalogRevision:COMMAND_CATALOG_REVISION}}:entry);if(store.snapshot().roster!.revision===1)await store.updateRoster(1,roster);const service=githubRead||new GitHubReadService(new GitHubReadStore(new GitHubReadAdapter({owner:"owner",repository:"repo",defaultBranch:"main",token:"secret"},fetcher)),"owner/repo");const audits:string[]=[];const results:string[]=[];const runtime=new CommandRuntime({store,ceiling:ROOM_COMMANDS,roster:()=>store.snapshot().roster!,canLaunch:()=>true,executeTask:async()=>({}),executePov:async()=>({}),deliverPov:async()=>undefined,deliverTask:async()=>undefined,publishStatus:async(id,text)=>{if(!audits.some((v)=>v.startsWith(id)))audits.push(`${id}:${text}`);},githubRead:service,publishGhResult:async(id,summary,text)=>{if(failPublication)throw new Error("controlled publication failure");if(!results.some((v)=>v.startsWith(id)))results.push(`${id}:${summary}\n\n${text}`);}});runtimes.push(runtime);return{root,store,runtime,audits,results};}
const response=(input:string|URL)=>{const url=new URL(input);if(url.pathname.endsWith("/pulls/98"))return new Response(JSON.stringify({number:98,title:"Read only",state:"open",draft:false,user:{login:"a"},updated_at:"2026-08-27T00:00:00Z",base:{ref:"main"},head:{ref:"branch",sha},body:"safe"}),{status:200});if(url.pathname.endsWith("/check-runs"))return new Response(JSON.stringify({check_runs:[{name:"test",status:"completed",conclusion:"success",completed_at:"2026-08-27T00:00:00Z",head_sha:sha,output:{summary:"green"}}]}),{status:200});return new Response("{}",{status:404});};
const submissionId=(clientSubmissionId:string)=>createHash("sha256").update([CANONICAL_ROOM_ID,"human","h1",clientSubmissionId].join("\0")).digest("hex").slice(0,32);
describe("durable GitHub command execution",()=>{
 it("preserves HTTP failure evidence across publication, replay and restart without refetching", async () => {
  const fetcher = vi.fn(async () => new Response("raw credential error must not escape", { status: 401, headers: { "x-github-request-id": "AB12:CD34:EF56" } }));
  const first = await fixture(fetcher);
  const invoker = { kind: "human" as const, id: "h1", displayName: "Ada" };
  const result = await first.runtime.submit("/gh issue 1", invoker, "http-diagnostic-restart") as { submissionId: string };
  expect(result).toMatchObject({ kind: "accepted", resultText: expect.stringContaining("HTTP 401") });
  expect(first.results[0]).toContain("GitHub rejected the credential");
  expect(first.results[0]).not.toContain("raw credential");
  expect(await first.runtime.getGhDiagnostic(invoker, result.submissionId)).toMatchObject({ kind: "github-diagnostic",
   items: [{ endpointFamily: "issue", failureKind: "upstream", statusClass: "4xx", httpStatus: 401, githubRequestId: "AB12:CD34:EF56" }] });
  await first.runtime.close(); runtimes.splice(runtimes.indexOf(first.runtime), 1);
  const secondFetch = vi.fn();
  const second = await fixture(secondFetch, { root: first.root, store: await RoomStore.open(first.root, path.join(first.root, "state")) });
  await second.runtime.initialize();
  expect(await second.runtime.submit("/gh issue 1", invoker, "http-diagnostic-restart")).toMatchObject({ duplicate: true, resultText: expect.stringContaining("HTTP 401") });
  expect(await second.runtime.getGhDiagnostic(invoker, result.submissionId)).toMatchObject({ items: [{ httpStatus: 401, githubRequestId: "AB12:CD34:EF56" }] });
  expect(secondFetch).not.toHaveBeenCalled();
 });
 it("converges human text and structured tools, resolves PR CI internally, and replays without refetch or duplicate projection",async()=>{const fetcher=vi.fn(async(input:string|URL)=>response(input));const api=await fixture(fetcher);const human=await api.runtime.submit("/gh ci 98",{kind:"human",id:"h1",displayName:"Ada"},"human-gh-ci-0001");expect(human).toMatchObject({kind:"accepted",duplicate:false,github:{kind:"ci",pullNumber:98},resultText:expect.stringContaining("test: completed/success")});expect(fetcher).toHaveBeenCalledTimes(2);expect(api.audits).toHaveLength(0);expect(api.results).toHaveLength(1);expect(api.results[0]).toContain("— Ada ran /gh — Read-only repository query");expect(api.results[0]).toContain("test: completed/success");expect(api.results[0]).not.toContain("ci 98");expect(await api.runtime.submit("/gh ci 98",{kind:"human",id:"h1",displayName:"Ada"},"human-gh-ci-0001")).toMatchObject({kind:"accepted",duplicate:true});expect(fetcher).toHaveBeenCalledTimes(2);expect(api.audits).toHaveLength(0);expect(api.results).toHaveLength(1);const tool=await api.runtime.submit({command:"gh",selector:{kind:"pr",number:98}},{kind:"agent",id:"codex-sol",displayName:"Sol"},"agent-gh-pr-0001");expect(tool).toMatchObject({kind:"accepted",github:{kind:"pr",pull:{number:98}}});});
 it("authorizes every replay before a cache hit and keeps diagnostics invoker-scoped",async()=>{const api=await fixture(async(input)=>response(input));const accepted=await api.runtime.submit("/gh pr 98",{kind:"agent",id:"codex-sol",displayName:"Sol"},"agent-gh-auth-01") as {submissionId:string};expect((await api.runtime.getGhDiagnostic({kind:"agent",id:"codex-sol",displayName:"Sol"},accepted.submissionId)).kind).toBe("github-diagnostic");expect((await api.runtime.getGhDiagnostic({kind:"human",id:"h1",displayName:"Ada"},accepted.submissionId)).kind).toBe("private-error");const before=api.store.snapshot().roster!;await api.store.updateRoster(before.revision,before.entries.map((entry)=>entry.agentId==="codex-sol"?{...entry,commandPermissions:{allowAll:false,allowed:["help"]}}:entry));expect(await api.runtime.submit({command:"gh",selector:{kind:"pr",number:98}},{kind:"agent",id:"codex-sol",displayName:"Sol"},"agent-gh-auth-01")).toMatchObject({kind:"private-error"});});
 it("persists terminal projections across a cold cache restart",async()=>{const firstFetch=vi.fn(async(input:string|URL)=>response(input));const first=await fixture(firstFetch);const result=await first.runtime.submit("/gh pr 98",{kind:"human",id:"h1",displayName:"Ada"},"human-gh-restart-01");expect(result).toMatchObject({kind:"accepted"});await first.runtime.close();runtimes.splice(runtimes.indexOf(first.runtime),1);const reopened=await RoomStore.open(first.root,path.join(first.root,"state"));const secondFetch=vi.fn(async()=>{throw new Error("must not fetch");});const second=await fixture(secondFetch,{root:first.root,store:reopened});await second.runtime.initialize();expect(await second.runtime.submit("/gh pr 98",{kind:"human",id:"h1",displayName:"Ada"},"human-gh-restart-01")).toMatchObject({kind:"accepted",duplicate:true,github:{kind:"pr"}});expect(secondFetch).not.toHaveBeenCalled();});
 it("retries a durable pending publication after restart without refetching or duplicating",async()=>{const firstFetch=vi.fn(async(input:string|URL)=>response(input));const first=await fixture(firstFetch,undefined,true);const accepted=await first.runtime.submit("/gh pr 98",{kind:"human",id:"h1",displayName:"Ada"},"human-gh-delivery-01") as {submissionId:string};expect(accepted).toMatchObject({kind:"accepted"});const pending=await first.store.getGhExecution(CANONICAL_ROOM_ID,accepted.submissionId);expect(pending).toMatchObject({status:"completed",deliveryStatus:"pending"});await first.runtime.close();runtimes.splice(runtimes.indexOf(first.runtime),1);const reopened=await RoomStore.open(first.root,path.join(first.root,"state"));const secondFetch=vi.fn(async()=>{throw new Error("must not fetch");});const second=await fixture(secondFetch,{root:first.root,store:reopened});await second.runtime.initialize();expect(second.results).toHaveLength(1);expect(await second.store.getGhExecution(CANONICAL_ROOM_ID,accepted.submissionId)).toMatchObject({status:"completed",deliveryStatus:"delivered"});expect(await second.runtime.submit("/gh pr 98",{kind:"human",id:"h1",displayName:"Ada"},"human-gh-delivery-01")).toMatchObject({kind:"accepted",duplicate:true});expect(second.results).toHaveLength(1);expect(secondFetch).not.toHaveBeenCalled();});
 it("attributes failures to the active endpoint family",async()=>{const api=await fixture(async()=>new Response("missing",{status:404}));const accepted=await api.runtime.submit("/gh issue 98",{kind:"human",id:"h1",displayName:"Ada"},"human-gh-failure-01") as {submissionId:string};expect(accepted).toMatchObject({kind:"accepted",resultText:expect.stringContaining("did not find")});expect(await api.store.getGhExecution(CANONICAL_ROOM_ID,accepted.submissionId)).toMatchObject({status:"failed",deliveryStatus:"delivered",diagnostics:[{endpointFamily:"issue",failureKind:"not-found"}]});});
 it("terminalizes queued recovery without a read when permission was revoked",async()=>{const fetcher=vi.fn(async(input:string|URL)=>response(input));const api=await fixture(fetcher);const createdAt="2026-08-27T12:00:00.000Z";const submission={submissionId:"revoked-recovery",roomId:CANONICAL_ROOM_ID,clientSubmissionId:"revoked-client",command:"gh" as const,invocation:{command:"gh" as const,selector:{kind:"pr" as const,number:98}},invoker:{kind:"agent" as const,id:"codex-sol",displayName:"Sol"},createdAt};const execution={executionId:"revoked-execution",roomId:CANONICAL_ROOM_ID,submissionId:submission.submissionId,status:"queued" as const,deliveryStatus:"pending" as const,authorizationLease:"legacy-static",projection:null,renderedText:null,failureKind:null,diagnostics:[] as const,createdAt,updatedAt:createdAt};expect(await api.store.acceptCommand({submission,audit:{auditId:"revoked-audit",roomId:CANONICAL_ROOM_ID,submissionId:submission.submissionId,command:"gh",invokerKind:"agent",invokerId:"codex-sol",targetAgentIds:[],createdAt},ghExecution:execution})).toMatchObject({kind:"accepted"});const roster=api.store.snapshot().roster!;await api.store.updateRoster(roster.revision,roster.entries.map((entry)=>entry.agentId==="codex-sol"?{...entry,commandPermissions:{allowAll:false,allowed:["help"]}}:entry));await api.runtime.initialize();expect(fetcher).not.toHaveBeenCalled();expect(await api.store.getGhExecution(CANONICAL_ROOM_ID,submission.submissionId)).toMatchObject({status:"failed",deliveryStatus:"delivered",failureKind:"forbidden"});expect(api.results).toHaveLength(0);});
 it("atomically adopts a lease for a pre-migration queued execution during restart recovery",async()=>{const fetcher=vi.fn(async(input:string|URL)=>response(input));const api=await fixture(fetcher);const createdAt="2026-08-27T12:00:00.000Z";const submission={submissionId:"legacy-queued",roomId:CANONICAL_ROOM_ID,clientSubmissionId:"legacy-client",command:"gh" as const,invocation:{command:"gh" as const,selector:{kind:"pr" as const,number:98}},invoker:{kind:"human" as const,id:"h1",displayName:"Ada"},createdAt};const execution={executionId:"legacy-execution",roomId:CANONICAL_ROOM_ID,submissionId:submission.submissionId,status:"queued" as const,deliveryStatus:"pending" as const,authorizationLease:null,projection:null,renderedText:null,failureKind:null,diagnostics:[] as const,createdAt,updatedAt:createdAt};expect(await api.store.acceptCommand({submission,audit:{auditId:"legacy-audit",roomId:CANONICAL_ROOM_ID,submissionId:submission.submissionId,command:"gh",invokerKind:"human",invokerId:"h1",targetAgentIds:[],createdAt},ghExecution:execution})).toMatchObject({kind:"accepted"});await api.runtime.initialize();expect(fetcher).toHaveBeenCalledTimes(1);expect(api.results).toHaveLength(1);expect(await api.store.getGhExecution(CANONICAL_ROOM_ID,submission.submissionId)).toMatchObject({status:"completed",deliveryStatus:"delivered",authorizationLease:"legacy-static"});});
 it("never publishes or returns a result when the authorization lease changes after execution",async()=>{const oldLease=`sha256:${"a".repeat(64)}`;let currentLease=oldLease;let release:undefined|(()=>void);let validationStarted:undefined|(()=>void);const started=new Promise<void>((resolve)=>{validationStarted=resolve;});let validations=0;const service:GitHubReadCommandService={authorize:async()=>currentLease,validateLease:async(_roomId,lease)=>{validations++;if(validations===1){validationStarted?.();await new Promise<void>((resolve)=>{release=resolve;});}if(lease!==currentLease)throw new GitHubReadFailure("connection-stale","none");},execute:async()=>({projection:{kind:"pr",repository:"owner/repo",pull:{number:98,title:"stale",state:"open",draft:false,author:"a",updatedAt:"2026-08-27T00:00:00Z",base:"main",head:"branch",headSha:sha,merged:false,body:"safe",truncated:false}},renderedText:"stale result",diagnostics:[],authorizationLease:oldLease}),failure:(error)=>{const failure=error instanceof GitHubReadFailure?error:new GitHubReadFailure("upstream","none");return{kind:failure.kind,text:"GitHub binding changed.",diagnostic:{endpointFamily:"pull-request",cacheOutcome:"miss",queueDelayMs:0,rateLimited:false,truncated:false,failureKind:failure.kind,statusClass:failure.statusClass,correlationId:"failure:lease"}};}};const api=await fixture(vi.fn(),undefined,false,service);const pending=api.runtime.submit("/gh pr 98",{kind:"human",id:"h1",displayName:"Ada"},"lease-publication-race");await started;currentLease=`sha256:${"b".repeat(64)}`;release?.();expect(await pending).toMatchObject({kind:"private-error",message:"GitHub binding changed."});expect(api.results).toHaveLength(0);const durable=await api.store.getGhExecution(CANONICAL_ROOM_ID,submissionId("lease-publication-race"));expect(durable).toBeDefined();expect(durable).toMatchObject({status:"failed",deliveryStatus:"delivered",failureKind:"connection-stale",projection:null});expect(durable?.renderedText).not.toContain("stale result");});
 it("fails closed for a delivery-pending completed record without the exact current lease",async()=>{const api=await fixture(vi.fn(async()=>{throw new Error("must not fetch");}));const createdAt="2026-08-27T12:00:00.000Z";const submission={submissionId:"legacy-terminal",roomId:CANONICAL_ROOM_ID,clientSubmissionId:"legacy-terminal-client",command:"gh" as const,invocation:{command:"gh" as const,selector:{kind:"pr" as const,number:98}},invoker:{kind:"human" as const,id:"h1",displayName:"Ada"},createdAt};const queued={executionId:"legacy-terminal-execution",roomId:CANONICAL_ROOM_ID,submissionId:submission.submissionId,status:"queued" as const,deliveryStatus:"pending" as const,authorizationLease:null,projection:null,renderedText:null,failureKind:null,diagnostics:[] as const,createdAt,updatedAt:createdAt};await api.store.acceptCommand({submission,audit:{auditId:"legacy-terminal-audit",roomId:CANONICAL_ROOM_ID,submissionId:submission.submissionId,command:"gh",invokerKind:"human",invokerId:"h1",targetAgentIds:[],createdAt},ghExecution:queued});const completed={...queued,status:"completed" as const,projection:{kind:"pr" as const,repository:"owner/repo",pull:{number:98,title:"stale",state:"open" as const,draft:false,author:"a",updatedAt:createdAt,base:"main",head:"branch",headSha:sha,merged:false,body:"safe",truncated:false}},renderedText:"stale result",updatedAt:"2026-08-27T12:01:00.000Z"};expect(await api.store.compareAndSetGhExecution(queued.updatedAt,completed)).toMatchObject({kind:"accepted"});await api.runtime.initialize();expect(api.results).toHaveLength(0);expect(await api.runtime.submit("/gh pr 98",{kind:"human",id:"h1",displayName:"Ada"},submission.clientSubmissionId)).toMatchObject({kind:"private-error"});expect(api.results).toHaveLength(0);});
});
