import { mkdtemp, rm } from "node:fs/promises";
import type { AddressInfo } from "node:net";
import os from "node:os";
import path from "node:path";
import express from "express";
import { afterEach, describe, expect, it } from "vitest";
import { registerCommandRoutes } from "./command-api.js";
import { CommandRuntime } from "./command-runtime.js";
import { DeveloperTeamRegistry, hashToken } from "./developer-team.js";
import { HumanPresenceRegistry } from "./human-presence.js";
import { HUMAN_SESSION_COOKIE, HumanSessions } from "./human-session.js";
import { RoomStore } from "./room-store.js";

const roots:string[]=[];afterEach(async()=>Promise.all(roots.splice(0).map((root)=>rm(root,{recursive:true,force:true}))));
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-api-"));roots.push(root);const store=await RoomStore.open(root,path.join(root,"state"));const humans=new HumanPresenceRegistry();const human=humans.join({name:"Ada"});const sessions=new HumanSessions();const cookie=`${HUMAN_SESSION_COOKIE}=${sessions.issue(human.id)}`;const commandToken="c".repeat(40);const readToken="r".repeat(40);const roomReadToken="o".repeat(40);const developers=new DeveloperTeamRegistry([{memberId:"codex-sol",revision:1,displayName:"Sol",roles:["AUTHOR"],capabilities:["COMMAND_RUN"],tokenHash:hashToken(commandToken),createdAt:new Date().toISOString()},{memberId:"diagnostic-reader",revision:1,displayName:"Reader",roles:["REVIEWER"],capabilities:["DIAGNOSTIC_READ"],tokenHash:hashToken(readToken),createdAt:new Date().toISOString()},{memberId:"room-reader",revision:1,displayName:"Room reader",roles:["REVIEWER"],capabilities:["ROOM_READ"],tokenHash:hashToken(roomReadToken),createdAt:new Date().toISOString()}]);const runtime=new CommandRuntime({store,roster:()=>store.snapshot().roster!,canLaunch:()=>true,executeTask:async(agent,_prompt,hooks)=>{await hooks.active(`g-${agent}`);return{generationId:`g-${agent}`,visibleMessages:["ok"]};},executePov:async()=>undefined,publishStatus:async()=>undefined,deliverTask:async()=>undefined});const app=express();app.use(express.json());registerCommandRoutes({app,runtime,store,humans,sessions,developers});const server=app.listen(0);await new Promise<void>((resolve)=>server.once("listening",resolve));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;const call=(url:string,init:RequestInit={})=>fetch(`${base}${url}`,{...init,headers:{"content-type":"application/json",Cookie:cookie,...(init.headers as Record<string,string>|undefined)}});return{call,runtime,commandToken,readToken,roomReadToken,close:()=>new Promise<void>((resolve,reject)=>server.close((error)=>error?reject(error):resolve()))};}

describe("command and diagnostic HTTP transports",()=>{
  it("returns rejected commands only in the invoking client's private envelope",async()=>{const api=await fixture();try{const response=await api.call("/api/commands",{method:"POST",body:JSON.stringify({text:"/poll not quoted",clientSubmissionId:"private-poll-01"})});expect(response.status).toBe(400);expect(await response.json()).toMatchObject({command:true,clientSubmissionId:"private-poll-01",result:{kind:"private-error"}});}finally{await api.close();}});

  it("accepts the message-route client identity used by human slash commands",async()=>{const api=await fixture();try{const response=await api.call("/api/commands",{method:"POST",body:JSON.stringify({text:"/help",clientMessageId:"message-route-command-01"})});expect(response.status).toBe(200);expect(await response.json()).toMatchObject({command:true,clientSubmissionId:"message-route-command-01",result:{kind:"private-help"}});}finally{await api.close();}});
  it("normalizes fractional poll page limits before SQLite binding",async()=>{const api=await fixture();try{expect((await api.call("/api/polls?limit=1.5")).status).toBe(200);}finally{await api.close();}});
  it("accepts human slash text and authenticated structured agent calls without trusting caller identity",async()=>{const api=await fixture();try{expect((await api.call("/api/commands",{method:"POST",body:JSON.stringify({text:"/help",clientSubmissionId:"human-help-01"})})).status).toBe(200);const agent=await api.call("/api/developer/commands",{method:"POST",headers:{authorization:`Bearer ${api.commandToken}`},body:JSON.stringify({clientSubmissionId:"agent-help-01",invocation:{command:"help"},agentId:"claude-sonnet"})});expect(agent.status).toBe(200);expect(await agent.json()).toMatchObject({command:true,clientSubmissionId:"agent-help-01",result:{kind:"private-help"}});expect((await api.call("/api/developer/commands",{method:"POST",body:JSON.stringify({clientSubmissionId:"agent-help-02",invocation:{command:"help"}})})).status).toBe(404);}finally{await api.close();}});
  it("keeps diagnostics pull-only, agent-scoped, bounded, searchable, and absent from unauthenticated responses",async()=>{const api=await fixture();try{await api.runtime.captureDiagnostic({agentId:"codex-sol",attemptId:"a1",generationId:"g1",correlationId:"only-once",prompt:"secret prompt",reason:"stalled",text:"safe marker"});expect((await api.call("/api/developer/diagnostics?agentId=codex-sol&search=marker")).status).toBe(404);const headers={authorization:`Bearer ${api.readToken}`};const list=await api.call("/api/developer/diagnostics?agentId=codex-sol&search=marker&limit=9999",{headers});expect(list.status).toBe(200);const body=await list.json() as {items:Array<{recordId:string}>};expect(body.items).toHaveLength(1);expect((await api.call(`/api/developer/diagnostics/${body.items[0]!.recordId}?agentId=claude-sonnet`,{headers})).status).toBe(404);expect((await api.call(`/api/developer/diagnostics/${body.items[0]!.recordId}?agentId=codex-sol`,{headers})).status).toBe(200);}finally{await api.close();}});
  it("denies a ROOM_READ-only credential access to every diagnostic route",async()=>{const api=await fixture();try{const headers={authorization:`Bearer ${api.roomReadToken}`};expect((await api.call("/api/developer/diagnostics?agentId=codex-sol",{headers})).status).toBe(404);expect((await api.call("/api/developer/diagnostics/missing?agentId=codex-sol",{headers})).status).toBe(404);}finally{await api.close();}});
});
