import type express from "express";
import { isActiveAgentId } from "../shared/participants.js";
import type { CommandInput } from "../shared/command-domain.js";
import { publicPollProjection, type CommandRecordStore } from "./command-record.js";
import type { CommandRuntime, CommandResponse } from "./command-runtime.js";
import type { DeveloperTeamRegistry } from "./developer-team.js";
import type { HumanPresenceRegistry } from "./human-presence.js";
import { sessionHuman, type HumanSessions } from "./human-session.js";
import { CANONICAL_ROOM_ID } from "./storage/room-repository.js";

function statusFor(result: CommandResponse) { return result.kind === "private-error" ? 400 : result.kind === "private-help" ? 200 : result.duplicate ? 200 : 202; }
export function sendCommandResponse(response: express.Response, result: CommandResponse, clientSubmissionId?:string) { return response.status(statusFor(result)).set("Cache-Control","no-store").json(clientSubmissionId ? { command:true, clientSubmissionId, result } : result.kind === "private-error" ? { error:result.message,kind:result.kind } : result); }

export async function submitHumanCommand(input:{request:express.Request;response:express.Response;runtime:CommandRuntime;humans:HumanPresenceRegistry;sessions:HumanSessions;text?:string}) {
  const human=sessionHuman(input.request,input.humans,input.sessions); if(!human)return input.response.status(401).json({error:"Join the room before running commands."});
  const command=(input.text??input.request.body?.text) as CommandInput; const clientSubmissionId=typeof input.request.body?.clientSubmissionId==="string"?input.request.body.clientSubmissionId.trim():"";
  return sendCommandResponse(input.response,await input.runtime.submit(command,{kind:"human",id:human.id,displayName:human.name},clientSubmissionId),clientSubmissionId);
}

export function registerCommandRoutes(input:{app:express.Express;runtime:CommandRuntime;store:CommandRecordStore;humans:HumanPresenceRegistry;sessions:HumanSessions;developers:DeveloperTeamRegistry}) {
  const {app,runtime,store,humans,sessions,developers}=input;
  const canReadDiagnostics=(authorization:string|undefined)=>developers.authenticate(authorization,"DIAGNOSTIC_READ")||developers.authenticate(authorization,"ROOM_READ");
  app.post("/api/commands",(request,response)=>submitHumanCommand({request,response,runtime,humans,sessions}));
  app.post("/api/developer/commands",async(request,response)=>{const authenticated=developers.authenticate(request.header("authorization"),"COMMAND_RUN");if(!authenticated)return response.status(404).json({error:"Not found."});if(!isActiveAgentId(authenticated.member.memberId))return response.status(403).json({error:"The authenticated member is not a room agent."});const clientSubmissionId=typeof request.body?.clientSubmissionId==="string"?request.body.clientSubmissionId.trim():"";return sendCommandResponse(response,await runtime.submit(request.body?.invocation as CommandInput,{kind:"agent",id:authenticated.member.memberId,displayName:authenticated.member.displayName},clientSubmissionId),clientSubmissionId);});
  app.post("/api/polls/:pollId/votes",async(request,response)=>{const human=sessionHuman(request,humans,sessions);if(!human)return response.status(401).json({error:"Join the room before voting."});const result=await runtime.vote(String(request.params.pollId),human.id,request.body?.optionIndex);return response.status(result.kind==="accepted"?result.duplicate?200:201:400).set("Cache-Control","no-store").json(result);});
  app.get("/api/polls",async(request,response)=>{if(!sessionHuman(request,humans,sessions))return response.status(401).json({error:"Join the room before viewing polls."});const polls=await store.listCommandPolls(CANONICAL_ROOM_ID);const items=await Promise.all(polls.map(async(poll)=>publicPollProjection(poll,await store.listCommandVotes(CANONICAL_ROOM_ID,poll.pollId))));return response.set("Cache-Control","no-store").json({items});});
  app.get("/api/polls/:pollId",async(request,response)=>{if(!sessionHuman(request,humans,sessions))return response.status(401).json({error:"Join the room before viewing polls."});const poll=await store.getCommandPoll(CANONICAL_ROOM_ID,String(request.params.pollId));if(!poll)return response.status(404).json({error:"Poll not found."});return response.set("Cache-Control","no-store").json(publicPollProjection(poll,await store.listCommandVotes(CANONICAL_ROOM_ID,poll.pollId)));});
  app.get("/api/developer/diagnostics",async(request,response)=>{if(!canReadDiagnostics(request.header("authorization")))return response.status(404).json({error:"Not found."});const agentId=typeof request.query.agentId==="string"&&isActiveAgentId(request.query.agentId)?request.query.agentId:null;if(!agentId)return response.status(400).json({error:"A valid room agent scope is required."});const search=typeof request.query.search==="string"?request.query.search:undefined;if(search&&search.length>200)return response.status(400).json({error:"Diagnostic search is limited to 200 characters."});const reason=typeof request.query.reason==="string"?request.query.reason.slice(0,80):undefined;const limit=Number(request.query.limit||50);return response.set("Cache-Control","no-store").json({items:await store.listDiagnostics(CANONICAL_ROOM_ID,{agentId,search,reason,limit:Number.isFinite(limit)?limit:50})});});
  app.get("/api/developer/diagnostics/:recordId",async(request,response)=>{if(!canReadDiagnostics(request.header("authorization")))return response.status(404).json({error:"Not found."});const agentId=typeof request.query.agentId==="string"&&isActiveAgentId(request.query.agentId)?request.query.agentId:null;if(!agentId)return response.status(400).json({error:"A valid room agent scope is required."});const record=await store.getDiagnostic(CANONICAL_ROOM_ID,agentId,String(request.params.recordId));return record?response.set("Cache-Control","no-store").json(record):response.status(404).json({error:"Diagnostic record not found."});});
}
