import type { GhSelector } from "../shared/command-domain.js";
import { GitHubReadFailure, type GitHubEndpointFamily, type GitHubFailureKind } from "./github-read-adapter.js";
import type { GitHubReadStore, GitHubReadDiagnostic } from "./github-read-store.js";
import type { GhExecutionDiagnostic, GhProjection } from "./command-record.js";

export const GH_MAX_RENDERED_OUTPUT=4_000;
function diagnostics(input:readonly GitHubReadDiagnostic[]):GhExecutionDiagnostic[]{return input.slice(0,8).map((item)=>({endpointFamily:item.family,cacheOutcome:item.cache,queueDelayMs:Math.max(0,Math.min(60_000,Math.floor(item.queueDelayMs))),rateLimited:item.rateLimited,truncated:item.truncated,failureKind:item.failureKind,statusClass:item.statusClass,correlationId:item.correlationId.slice(0,100)}));}
function failureText(kind:GitHubFailureKind){if(kind==="not-found")return "GitHub did not find that repository item.";if(kind==="forbidden")return "GitHub denied this read.";if(kind==="rate-limited")return "GitHub is temporarily rate limiting reads.";if(kind==="timeout")return "GitHub did not respond before the bounded timeout.";if(kind==="saturated")return "The bounded GitHub read queue is full; try again shortly.";if(kind==="configuration")return "GitHub reads are not configured.";return "GitHub could not provide a valid bounded response.";}
export function renderGhProjection(value:GhProjection){let text:string;if(value.kind==="pr"){const p=value.pull;text=`GitHub PR #${p.number} — ${p.title}\n${p.state}${p.merged?" · merged":""}${p.draft?" · draft":""} · @${p.author} · ${p.base} ← ${p.head}\nUpdated ${p.updatedAt}${p.body?`\n${p.body}`:""}`;}else if(value.kind==="issue"){const i=value.issue;text=`GitHub issue #${i.number} — ${i.title}\n${i.state} · @${i.author} · ${i.comments} comments${i.labels.length?` · ${i.labels.join(", ")}`:""}\nUpdated ${i.updatedAt}${i.body?`\n${i.body}`:""}`;}else if(value.kind==="ci"){text=`GitHub CI${value.pullNumber?` for PR #${value.pullNumber}`:" for the default branch"}\n${value.checks.length?value.checks.map((c)=>`${c.name}: ${c.status}${c.conclusion?`/${c.conclusion}`:""}${c.annotation?` — ${c.annotation}`:""}`).join("\n"):"No checks were reported."}`;}else{text=`Recent GitHub activity for ${value.repository}\nPull requests:\n${value.pulls.map((p)=>`#${p.number} ${p.title} — ${p.state}`).join("\n")||"None"}\nIssues:\n${value.issues.map((i)=>`#${i.number} ${i.title} — ${i.state}`).join("\n")||"None"}\nCI:\n${value.runs.map((r)=>`${r.name}: ${r.status}${r.conclusion?`/${r.conclusion}`:""}`).join("\n")||"None"}`;}return text.slice(0,GH_MAX_RENDERED_OUTPUT);}

export class GitHubReadService{
  constructor(private readonly store:GitHubReadStore,readonly repositoryLabel:string){}
  async execute(selector:GhSelector):Promise<{projection:GhProjection;renderedText:string;diagnostics:readonly GhExecutionDiagnostic[]}>{const records:GitHubReadDiagnostic[]=[];const read=async(query:Parameters<GitHubReadStore["get"]>[0])=>{try{const outcome=await this.store.get(query);records.push(outcome.diagnostic);return outcome.value;}catch(error){const failure=error instanceof GitHubReadFailure?error:new GitHubReadFailure("upstream","none");throw new GitHubReadFailure(failure.kind,failure.statusClass,failure.retryAfterMs,query.family);}};let projection:GhProjection;if(selector.kind==="recent"){const [pulls,issues,runs]=await Promise.all([read({family:"recent-pulls"}),read({family:"recent-issues"}),read({family:"recent-runs"})]);if(pulls.family!=="recent-pulls"||issues.family!=="recent-issues"||runs.family!=="recent-runs")throw new GitHubReadFailure("invalid-response","none",null,"recent-pulls");projection={kind:"recent",repository:this.repositoryLabel,pulls:pulls.items,issues:issues.items,runs:runs.items,truncated:pulls.truncated||issues.truncated||runs.truncated};}else if(selector.kind==="pr"){const result=await read({family:"pull-request",number:selector.number});if(result.family!=="pull-request")throw new GitHubReadFailure("invalid-response","none",null,"pull-request");projection={kind:"pr",repository:this.repositoryLabel,pull:result.item};}else if(selector.kind==="issue"){const result=await read({family:"issue",number:selector.number});if(result.family!=="issue")throw new GitHubReadFailure("invalid-response","none",null,"issue");projection={kind:"issue",repository:this.repositoryLabel,issue:result.item};}else{let sha:string;let pullNumber:number|null=null;if(selector.number!==undefined){const pr=await read({family:"pull-request",number:selector.number});if(pr.family!=="pull-request"||!/^[0-9a-f]{40}$/i.test(pr.item.headSha))throw new GitHubReadFailure("invalid-response","none",null,"pull-request");sha=pr.item.headSha;pullNumber=selector.number;}else{const runs=await read({family:"recent-runs"});if(runs.family!=="recent-runs"||!/^[0-9a-f]{40}$/i.test(runs.items[0]?.sha||""))throw new GitHubReadFailure("invalid-response","none",null,"recent-runs");sha=runs.items[0]!.sha;}const checks=await read({family:"check-runs",sha});if(checks.family!=="check-runs")throw new GitHubReadFailure("invalid-response","none",null,"check-runs");projection={kind:"ci",repository:this.repositoryLabel,pullNumber,checks:checks.items,truncated:checks.truncated};}return{projection,renderedText:renderGhProjection(projection),diagnostics:diagnostics(records)};}
  failure(error:unknown,fallbackFamily:GitHubEndpointFamily="recent-pulls"){const failure=error instanceof GitHubReadFailure?error:new GitHubReadFailure("upstream","none");return{kind:failure.kind,text:failureText(failure.kind),diagnostic:{endpointFamily:failure.endpointFamily||fallbackFamily,cacheOutcome:"miss" as const,queueDelayMs:0,rateLimited:failure.kind==="rate-limited",truncated:false,failureKind:failure.kind,statusClass:failure.statusClass,correlationId:`failure:${failure.kind}`}};}
}
