import {describe,expect,it,vi} from "vitest";
import {GitHubReadAdapter,GitHubReadFailure,type GitHubReadFetch} from "./github-read-adapter.js";
import {GitHubReadStore} from "./github-read-store.js";

const token="ghp_SECRET_SENTINEL_DO_NOT_LEAK";const sha="0123456789abcdef0123456789abcdef01234567";
const binding={owner:"virusimmortal00",repository:"AllMyFriendsAreAgents",defaultBranch:"main",token};
function json(value:unknown,status=200,headers:Record<string,string>={}){return new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json",...headers}});}
function pr(number=98){return{number,title:`PR ${number} ${token} ${"x".repeat(300)}`,state:"open",draft:false,user:{login:"author"},updated_at:"2026-08-27T00:00:00Z",base:{ref:"main"},head:{ref:"branch",sha},body:`Authorization: Bearer ${token} ${"b".repeat(1400)}`};}

describe("narrow GitHub read adapter",()=>{
  it("owns the HTTPS host, GET method, endpoint and query shape while sanitizing before return",async()=>{let seen:unknown[]=[];const fetcher:GitHubReadFetch=vi.fn(async(input,init)=>{seen=[String(input),init];return json(pr());});const value=await new GitHubReadAdapter(binding,fetcher).read({family:"pull-request",number:98});expect(seen[0]).toBe("https://api.github.com/repos/virusimmortal00/AllMyFriendsAreAgents/pulls/98");expect(seen[1]).toMatchObject({method:"GET",redirect:"error",body:undefined});expect(JSON.stringify(value)).not.toContain(token);expect(value).toMatchObject({family:"pull-request",item:{number:98,truncated:true}});expect(JSON.stringify(value).length).toBeLessThan(2500);});
  it.each([[403,{},"forbidden"],[404,{},"not-found"],[429,{"retry-after":"999"},"rate-limited"],[403,{"x-ratelimit-remaining":"0"},"rate-limited"],[500,{},"upstream"]] as const)("maps %s without raw response exposure",async(status,headers,kind)=>{const adapter=new GitHubReadAdapter(binding,async()=>new Response(`raw ${token}`,{status,headers}));await expect(adapter.read({family:"issue",number:1})).rejects.toMatchObject({kind,message:`GitHub read failed (${kind}).`});});
  it("rejects unsafe numbers and caller-like SHAs before fetch",async()=>{const fetcher=vi.fn();const adapter=new GitHubReadAdapter(binding,fetcher as never);await expect(adapter.read({family:"pull-request",number:0})).rejects.toMatchObject({kind:"configuration"});await expect(adapter.read({family:"check-runs",sha:"main"})).rejects.toMatchObject({kind:"configuration"});expect(fetcher).not.toHaveBeenCalled();});
  it("bounds timeout and invalid-response failures without retrying",async()=>{const timeout=vi.fn(async()=>{throw new DOMException("secret raw timeout","AbortError");});await expect(new GitHubReadAdapter(binding,timeout).read({family:"issue",number:1})).rejects.toMatchObject({kind:"timeout"});expect(timeout).toHaveBeenCalledTimes(1);const invalid=vi.fn(async()=>new Response("not-json",{status:200}));await expect(new GitHubReadAdapter(binding,invalid).read({family:"issue",number:1})).rejects.toMatchObject({kind:"invalid-response"});expect(invalid).toHaveBeenCalledTimes(1);});
});

describe("shared GitHub read store",()=>{
  it("coalesces identical misses and refreshes exactly at expiresAt with an injected monotonic clock",async()=>{let now=0;let release!:(value:Response)=>void;let calls=0;const fetcher:GitHubReadFetch=()=>{calls++;return new Promise((resolve)=>{release=resolve;});};const store=new GitHubReadStore(new GitHubReadAdapter(binding,fetcher),{ttlMs:60_000,clock:{now:()=>now}});const first=store.get({family:"pull-request",number:98});const second=store.get({family:"pull-request",number:98});release(json(pr()));expect((await Promise.all([first,second])).map((item)=>item.diagnostic.cache)).toEqual(["miss","coalesced"]);expect(calls).toBe(1);now=59_999;expect((await store.get({family:"pull-request",number:98})).diagnostic.cache).toBe("hit");now=60_000;const refresh=store.get({family:"pull-request",number:98});release(json(pr()));expect((await refresh).diagnostic.cache).toBe("refresh");expect(calls).toBe(2);});
  it("bounds distinct-key scheduling and deterministically evicts the least recently used entry",async()=>{let release!:(value:Response)=>void;const slow:GitHubReadFetch=()=>new Promise((resolve)=>{release=resolve;});const saturated=new GitHubReadStore(new GitHubReadAdapter(binding,slow),{maxActive:1,maxQueued:0});const active=saturated.get({family:"pull-request",number:1});await expect(saturated.get({family:"pull-request",number:2})).rejects.toMatchObject({kind:"saturated"});release(json(pr(1)));await active;let calls=0;const store=new GitHubReadStore(new GitHubReadAdapter(binding,async()=>json(pr(++calls))),{maxEntries:2});await store.get({family:"pull-request",number:1});await store.get({family:"pull-request",number:2});await store.get({family:"pull-request",number:1});await store.get({family:"pull-request",number:3});expect(store.inspect().entries).toBe(2);await store.get({family:"pull-request",number:2});expect(calls).toBe(4);});
  it("protects a successful entry when an expired refresh fails",async()=>{let now=0;let calls=0;const adapter=new GitHubReadAdapter(binding,async()=>++calls===1?json(pr()):Promise.reject(new Error("raw")));const store=new GitHubReadStore(adapter,{ttlMs:1,clock:{now:()=>now}});await store.get({family:"pull-request",number:98});now=1;await expect(store.get({family:"pull-request",number:98})).rejects.toBeInstanceOf(GitHubReadFailure);expect(store.inspect().entries).toBe(1);});
});
