import { randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import path from "node:path";
import {
  INVESTIGATION_POLICY_VERSION, canTransitionInvestigation, checkpointDigest, investigationIsNonterminal, investigationProjectHash,
  makeInvestigationEvent, redactInvestigationText, type InvestigationBudget, type InvestigationCheckpoint, type InvestigationEvidenceRef,
  type InvestigationInboxEntry, type InvestigationPolicy, type InvestigationRecord, type InvestigationSignal, type InvestigationStatus, type InvestigationUsage,
} from "./investigation-record.js";
import { InvestigationStore } from "./investigation-store.js";
import type { RoomRepository } from "./storage/room-repository.js";
import type { AgentId } from "./types.js";

export const DEFAULT_INVESTIGATION_BUDGET: InvestigationBudget = Object.freeze({ timeMs: 60_000, tokenLimit: 6_000, toolCallLimit: 16, retryLimit: 1 });
const MAX_BUDGET: InvestigationBudget = Object.freeze({ timeMs: 300_000, tokenLimit: 64_000, toolCallLimit: 40, retryLimit: 2 });
const CAPABILITIES = ["READ_PROJECT", "READ_OBSERVABILITY", "RUN_READ_ONLY_TESTS"] as const;

export interface InvestigationExecutorInput {
  readonly investigationId: string; readonly attempt: number; readonly owner: AgentId; readonly objective: string; readonly trigger: string;
  readonly contextSnapshot: string; readonly evidenceRefs: readonly InvestigationEvidenceRef[]; readonly projectPath: string;
  readonly capabilities: typeof CAPABILITIES; readonly excludedCapabilities: readonly string[]; readonly forbiddenProviderSessionIds: readonly string[];
  readonly remainingBudget: Omit<InvestigationBudget, "retryLimit">; readonly checkpoint: InvestigationCheckpoint | null; readonly signal: AbortSignal;
  readonly progress: (state: "WAITING_TOOL" | "RUNNING", detail?: string, checkpoint?: { summary: string; opaqueState: string }) => Promise<boolean>;
}
export interface InvestigationExecutorResult { readonly providerSessionId: string; readonly summary: string; readonly evidenceRefs?: readonly InvestigationEvidenceRef[]; readonly unresolvedQuestions?: readonly string[]; readonly usage: { readonly tokens: number; readonly toolCalls: number } }
export interface InvestigationExecutor { dispatch(input: InvestigationExecutorInput): Promise<InvestigationExecutorResult> }
export interface InvestigationProgressChannel { handleProgress(id: string, attempt: number, authorization: string | undefined, body: unknown): Promise<"accepted" | "unauthorized" | "invalid" | "stale"> }

export class HttpInvestigationExecutor implements InvestigationExecutor, InvestigationProgressChannel {
  private readonly pending = new Map<string, { token: string; progress: InvestigationExecutorInput["progress"] }>();
  constructor(private readonly url: string, private readonly authorization?: string, private readonly progressBaseUrl = "http://127.0.0.1:53147") {}
  async dispatch(input: InvestigationExecutorInput): Promise<InvestigationExecutorResult> {
    const key = `${input.investigationId}\0${input.attempt}`; const token = randomBytes(32).toString("base64url"); this.pending.set(key, { token, progress: input.progress });
    try {
      const progressUrl = new URL(`/api/investigation-executor/progress/${encodeURIComponent(input.investigationId)}/${input.attempt}`, this.progressBaseUrl).toString();
      const response = await fetch(this.url, { method: "POST", signal: input.signal, headers: { "content-type": "application/json", ...(this.authorization ? { authorization: this.authorization } : {}) }, body: JSON.stringify({
        schemaVersion: 1, investigationId: input.investigationId, attempt: input.attempt, owner: input.owner, objective: input.objective, trigger: input.trigger,
        contextSnapshot: input.contextSnapshot, evidenceRefs: input.evidenceRefs, projectPath: input.projectPath, capabilities: input.capabilities,
        excludedCapabilities: input.excludedCapabilities, forbiddenProviderSessionIds: input.forbiddenProviderSessionIds, remainingBudget: input.remainingBudget,
        checkpoint: input.checkpoint, requireFreshProviderSession: true, progress: { url: progressUrl, authorization: `Bearer ${token}` },
      }) });
      if (!response.ok) throw new Error(`Investigation executor returned HTTP ${response.status}.`);
      const body = await response.json() as Partial<InvestigationExecutorResult>;
      if (typeof body.providerSessionId !== "string" || !body.providerSessionId.trim() || typeof body.summary !== "string" || !body.usage || !Number.isSafeInteger(body.usage.tokens) || !Number.isSafeInteger(body.usage.toolCalls)) throw new Error("Investigation executor returned an invalid bounded result.");
      return { providerSessionId: body.providerSessionId, summary: body.summary, evidenceRefs: Array.isArray(body.evidenceRefs) ? body.evidenceRefs : [], unresolvedQuestions: Array.isArray(body.unresolvedQuestions) ? body.unresolvedQuestions.map(String) : [], usage: body.usage };
    } finally { if (this.pending.get(key)?.token === token) this.pending.delete(key); }
  }
  async handleProgress(id: string, attempt: number, authorization: string | undefined, body: unknown) {
    const pending = this.pending.get(`${id}\0${attempt}`); if (!pending) return "stale" as const;
    if (!authorization?.startsWith("Bearer ")) return "unauthorized" as const; const supplied = Buffer.from(authorization.slice(7)); const expected = Buffer.from(pending.token);
    if (supplied.length !== expected.length || !timingSafeEqual(supplied, expected)) return "unauthorized" as const;
    const value = body as { state?: unknown; detail?: unknown; checkpoint?: unknown } | null;
    if (!value || (value.state !== "WAITING_TOOL" && value.state !== "RUNNING") || value.detail !== undefined && (typeof value.detail !== "string" || value.detail.length > 2_000)) return "invalid" as const;
    const checkpoint = value.checkpoint as { summary?: unknown; opaqueState?: unknown } | undefined;
    if (checkpoint && (typeof checkpoint.summary !== "string" || checkpoint.summary.length > 2_000 || typeof checkpoint.opaqueState !== "string" || checkpoint.opaqueState.length > 8_000)) return "invalid" as const;
    return await pending.progress(value.state, value.detail as string | undefined, checkpoint ? { summary: checkpoint.summary as string, opaqueState: checkpoint.opaqueState as string } : undefined) ? "accepted" as const : "stale" as const;
  }
}

export type InvestigationResult<T> = { readonly kind: "ok"; readonly value: T } | { readonly kind: "not_found" } | { readonly kind: "conflict" | "rejected"; readonly reason: string };
export class InvestigationService {
  private readonly active = new Map<string, AbortController>(); private closed = false; private pumping = false;
  constructor(private readonly store: InvestigationStore, private readonly rooms: RoomRepository, private readonly executor: InvestigationExecutor, private readonly options: {
    now?: () => Date; configuredEnabled?: boolean; maxConcurrentGlobal?: number; emergencyStopped?: () => boolean | Promise<boolean>; onTransition?: () => void; onError?: (error: unknown) => void;
  } = {}) {}
  async initialize() {
    if (!await this.store.policy()) { const now = this.now(); const policy: InvestigationPolicy = { schemaVersion: 1, policyVersion: INVESTIGATION_POLICY_VERSION, revision: 1, enabled: this.options.configuredEnabled === true, projectPathHash: investigationProjectHash(this.rooms.snapshot().settings.projectPath), maxConcurrentGlobal: Math.max(1, Math.min(8, this.options.maxConcurrentGlobal ?? 2)), maxConcurrentPerAgent: 1, defaultBudget: DEFAULT_INVESTIGATION_BUDGET, maxInboxEntriesPerAgent: 20, inboxTtlMs: 7 * 24 * 60 * 60_000, updatedAt: now, updatedBy: "server-initialization" }; await this.store.setPolicy(0, policy); }
    await this.reconcile(); this.schedulePump();
  }
  async policy() { return this.store.policy(); } async list(owner?: AgentId) { return this.store.list(owner); } async audit(id: string) { return this.store.audit(id); }
  activeCount() { return this.active.size; }
  async updatePolicy(expectedRevision: number, enabled: boolean, actor: string) { const current = await this.store.policy(); if (!current) return { kind: "not_found" } as const; const next = { ...current, revision: current.revision + 1, enabled, updatedAt: this.now(), updatedBy: actor }; if (!await this.store.setPolicy(expectedRevision, next)) return { kind: "conflict", reason: "Investigation policy changed concurrently." } as const; await this.cancelAll("Investigation policy revision changed."); this.changed(); return { kind: "ok", value: next } as const; }
  async request(input: { owner: AgentId; objective: string; trigger: string; signal: InvestigationSignal; evidenceRefs?: readonly InvestigationEvidenceRef[]; contextSnapshot?: string; budget?: Partial<InvestigationBudget> }): Promise<InvestigationResult<InvestigationRecord>> {
    if (this.closed) return { kind: "rejected", reason: "Server is shutting down." }; const policy = await this.validPolicy(); if ("reason" in policy) return { kind: "rejected", reason: policy.reason }; if (await this.stopped()) return { kind: "rejected", reason: "Emergency stop is active." };
    if (!["AGENT_DECISION", "AUTHENTICATED_HUMAN", "TRUSTED_POLICY"].includes(input.signal)) return { kind: "rejected", reason: "A trusted launch signal is required." };
    const objective = redactInvestigationText(input.objective?.trim() || "").trim(); const trigger = redactInvestigationText(input.trigger?.trim() || "").trim(); if (!objective || objective.length > 4_000 || !trigger || trigger.length > 1_000) return { kind: "rejected", reason: "A bounded objective and trigger are required." };
    const evidenceRefs = input.evidenceRefs || []; if (!this.validEvidence(evidenceRefs)) return { kind: "rejected", reason: "Evidence references must resolve to current room or local project evidence." };
    if (input.signal !== "AUTHENTICATED_HUMAN" && evidenceRefs.length === 0) return { kind: "rejected", reason: "Autonomous investigations require corroboratable evidence references." };
    const budget = boundedBudget(input.budget, policy.defaultBudget); if (!budget) return { kind: "rejected", reason: "Investigation budget exceeds policy limits." };
    const now = this.now(); const record: InvestigationRecord = { schemaVersion: 1, investigationId: randomUUID(), revision: 1, owner: input.owner, objective, trigger, signal: input.signal, evidenceRefs: structuredClone(evidenceRefs), contextSnapshot: redactInvestigationText(input.contextSnapshot || "").slice(0, 16_000), projectPathHash: policy.projectPathHash, policyRevision: policy.revision, policyVersion: policy.policyVersion, capabilities: CAPABILITIES, status: "REQUESTED", budget, usage: { elapsedMs: 0, tokens: 0, toolCalls: 0, attempts: 0 }, providerSessionId: null, checkpoint: null, resultSummary: null, resultEvidence: [], unresolvedQuestions: [], resultWaiting: false, blocker: null, createdAt: now, startedAt: null, updatedAt: now, completedAt: null };
    if (!await this.store.create(record, await this.event(record, null, "REQUESTED", "Trusted bounded investigation requested."))) return { kind: "conflict", reason: "This agent already has a nonterminal investigation." };
    const queued = await this.transition(record, "QUEUED", "QUEUED", "Investigation admitted to the bounded queue."); this.changed(); this.schedulePump(); return { kind: "ok", value: queued || record };
  }
  async cancel(id: string, reason = "Cancelled by a human."): Promise<InvestigationResult<InvestigationRecord>> { const record = await this.store.get(id); if (!record) return { kind: "not_found" }; if (!investigationIsNonterminal(record)) return { kind: "conflict", reason: "Only a nonterminal investigation can be cancelled." }; const next = await this.transition(record, "CANCELLED", "CANCELLED", reason, { blocker: reason, completedAt: this.now() }); if (!next) return { kind: "conflict", reason: "Investigation changed concurrently." }; this.active.get(id)?.abort(reason); this.changed(); this.schedulePump(); return { kind: "ok", value: next }; }
  async resume(id: string): Promise<InvestigationResult<InvestigationRecord>> { const record = await this.store.get(id); if (!record) return { kind: "not_found" }; if (record.status !== "BLOCKED" && record.status !== "CHECKPOINTED") return { kind: "conflict", reason: "Only blocked or checkpointed investigations can resume." }; if (record.status === "CHECKPOINTED" && !record.checkpoint) return { kind: "rejected", reason: "A valid durable checkpoint is required." }; const validation = await this.revalidate(record); if (validation) return { kind: "rejected", reason: validation }; const queued = await this.transition(record, "QUEUED", "RESUMED", "Resume authorized under current policy.", { blocker: null }); if (!queued) return { kind: "conflict", reason: "Investigation changed concurrently." }; this.changed(); this.schedulePump(); return { kind: "ok", value: queued }; }
  async inbox(owner: AgentId) { await this.archiveExpired(owner); return this.store.inbox(owner); }
  async acknowledge(entryId: string, close = false): Promise<InvestigationResult<InvestigationInboxEntry>> { const entry = await this.store.getInbox(entryId); if (!entry) return { kind: "not_found" }; if (entry.status === "CLOSED" || entry.status === "ARCHIVED") return { kind: "conflict", reason: "Inbox entry is already closed." }; if (entry.status === "ACKNOWLEDGED" && !close) return { kind: "ok", value: entry }; const next = { ...entry, revision: entry.revision + 1, status: close ? "CLOSED" as const : "ACKNOWLEDGED" as const, updatedAt: this.now() }; if (!await this.store.updateInbox(entry.revision, next)) return { kind: "conflict", reason: "Inbox entry changed concurrently." }; if (close) { const job = await this.store.get(entry.investigationId); if (job?.status === "COMPLETED") await this.transition(job, "ACKNOWLEDGED", "ACKNOWLEDGED", "Investigation result closed by a human.", { resultWaiting: false }); } this.changed(); return { kind: "ok", value: next }; }
  async contextForAgent(owner: AgentId, characterBudget = 3_000, limit = 3) { let remaining = Math.max(0, Math.min(8_000, characterBudget)); const entries = (await this.inbox(owner)).filter((entry) => entry.status === "UNREAD" || entry.status === "ACKNOWLEDGED").slice(0, Math.max(0, Math.min(10, limit))); return entries.flatMap((entry) => { if (!remaining) return []; const summary = redactInvestigationText(entry.summary).slice(0, remaining); remaining -= summary.length; return summary ? [{ inboxEntryId: entry.inboxEntryId, investigationId: entry.investigationId, summary, evidenceRefs: entry.evidenceRefs, unresolvedQuestions: entry.unresolvedQuestions, createdAt: entry.createdAt }] : []; }); }
  async reconcile() { const jobs = await this.store.list(); for (const job of jobs) { if (job.status === "RUNNING" || job.status === "WAITING_TOOL") { if (job.checkpoint) await this.transition(job, "CHECKPOINTED", "RESTART_CHECKPOINTED", "Executor process disappeared during restart; durable checkpoint retained.", { blocker: "Ready to resume from the last durable checkpoint." }); else await this.transition(job, "BLOCKED", "RESTART_BLOCKED", "Executor process disappeared during restart; no checkpoint can be assumed running.", { blocker: "Restart interrupted work before a durable checkpoint." }); } else if (investigationIsNonterminal(job)) { const invalid = await this.revalidate(job); if (invalid) await this.cancel(job.investigationId, invalid); } } for (const owner of new Set(jobs.map((job) => job.owner))) await this.reconcileInboxDisposition(owner); }
  async cancelAll(reason: string) { for (const job of await this.store.list()) if (investigationIsNonterminal(job)) await this.cancel(job.investigationId, reason); }
  async shutdown() { this.closed = true; for (const controller of this.active.values()) controller.abort("server shutdown"); for (const job of await this.store.list()) { if ((job.status === "RUNNING" || job.status === "WAITING_TOOL") && job.checkpoint) await this.transition(job, "CHECKPOINTED", "SHUTDOWN_CHECKPOINTED", "Server shutdown retained the last durable checkpoint.", { blocker: "Server stopped; resume from checkpoint after restart." }); else if (job.status === "RUNNING" || job.status === "WAITING_TOOL" || job.status === "QUEUED" || job.status === "REQUESTED") await this.cancel(job.investigationId, "Server shutdown cancelled bounded investigation work."); } return this.active.size; }
  private schedulePump() { if (!this.pumping && !this.closed) queueMicrotask(() => void this.pump().catch((error) => this.error(error))); }
  private async pump() { if (this.pumping || this.closed) return; this.pumping = true; try { const policy = await this.store.policy(); if (!policy?.enabled) return; for (const job of await this.store.list()) { if (this.active.size >= policy.maxConcurrentGlobal) break; if (job.status === "QUEUED") void this.run(job.investigationId).catch((error) => this.error(error)); } } finally { this.pumping = false; } }
  private async run(id: string) { if (this.closed) return; let job = await this.store.get(id); if (!job || job.status !== "QUEUED" || this.active.has(id)) return; const invalid = await this.revalidate(job); if (invalid) { await this.cancel(id, invalid); return; } const now = this.now(); const running = await this.transition(job, "RUNNING", "DISPATCHED", "Fresh read-only provider session dispatch started.", { startedAt: job.startedAt ?? now, usage: { ...job.usage, attempts: job.usage.attempts + 1 } }); if (!running) return; job = running; if (this.closed) { await this.cancel(id, "Server shutdown cancelled bounded investigation work."); return; }
    const controller = new AbortController(); this.active.set(id, controller); const remainingTime = job.budget.timeMs - job.usage.elapsedMs; const timer = setTimeout(() => controller.abort("time budget exhausted"), Math.max(1, remainingTime)); timer.unref(); const started = Date.now();
    try { const result = await this.executor.dispatch({ investigationId: id, attempt: job.usage.attempts, owner: job.owner, objective: job.objective, trigger: job.trigger, contextSnapshot: job.contextSnapshot, evidenceRefs: job.evidenceRefs, projectPath: this.rooms.snapshot().settings.projectPath, capabilities: CAPABILITIES, excludedCapabilities: ["TASK_AUTHORITY", "EDIT", "EXTERNAL_REQUEST", "COMMIT", "PUSH", "MERGE", "DEPLOY", "PUBLISH"], forbiddenProviderSessionIds: Object.values(this.rooms.snapshot().sessions).map((session) => session.id), remainingBudget: { timeMs: remainingTime, tokenLimit: job.budget.tokenLimit - job.usage.tokens, toolCallLimit: job.budget.toolCallLimit - job.usage.toolCalls }, checkpoint: job.checkpoint, signal: controller.signal, progress: (state, detail, checkpoint) => this.progress(id, job!.usage.attempts, state, detail, checkpoint) });
      const current = await this.store.get(id); if (!current || (current.status !== "RUNNING" && current.status !== "WAITING_TOOL")) return; const usage = addUsage(current.usage, Date.now() - started, result.usage); const invalidAfterRun = await this.revalidate(current); if (invalidAfterRun) { await this.transition(current, "CANCELLED", "AUTHORITY_REVOKED", invalidAfterRun, { usage, blocker: invalidAfterRun, completedAt: this.now() }); return; } const foregroundSessions = new Set(Object.values(this.rooms.snapshot().sessions).map((session) => session.id)); if (foregroundSessions.has(result.providerSessionId) || current.providerSessionId && current.providerSessionId !== result.providerSessionId) { await this.fail(current, usage, "Executor reused or changed a foreground provider session."); return; } if (overBudget(current.budget, usage)) { await this.fail(current, usage, "Investigation budget exhausted."); return; }
      const summary = redactInvestigationText(result.summary).trim().slice(0, 16_000); if (!summary) { await this.fail(current, usage, "Investigation executor returned an empty public summary."); return; } const evidence = (result.evidenceRefs || []).filter((ref) => this.validEvidence([ref])).slice(0, 32); const questions = (result.unresolvedQuestions || []).map((q) => redactInvestigationText(q).slice(0, 500)).filter(Boolean).slice(0, 16); const completedAt = this.now(); const completed = this.next(current, "COMPLETED", { usage, providerSessionId: result.providerSessionId, resultSummary: summary, resultEvidence: evidence, unresolvedQuestions: questions, resultWaiting: true, blocker: null, completedAt, updatedAt: completedAt }); const entry: InvestigationInboxEntry = { schemaVersion: 1, inboxEntryId: randomUUID(), revision: 1, investigationId: id, owner: current.owner, status: "UNREAD", summary, evidenceRefs: evidence, unresolvedQuestions: questions, createdAt: completedAt, updatedAt: completedAt, expiresAt: new Date(Date.parse(completedAt) + (await this.store.policy())!.inboxTtlMs).toISOString() }; const event = await this.event(completed, current.status, "COMPLETED", "Evidence-backed result placed in the private agent inbox."); await this.store.complete(current.revision, completed, entry, event, (await this.store.policy())!.maxInboxEntriesPerAgent); await this.reconcileInboxDisposition(current.owner); this.changed();
    } catch (error) { const current = await this.store.get(id); if (current && (current.status === "RUNNING" || current.status === "WAITING_TOOL")) { const usage = addUsage(current.usage, Date.now() - started, { tokens: 0, toolCalls: 0 }); if (controller.signal.aborted) await this.fail(current, usage, String(controller.signal.reason || "Investigation cancelled.")); else if (current.usage.attempts <= current.budget.retryLimit && current.checkpoint) await this.transition(current, "CHECKPOINTED", "RETRY_CHECKPOINTED", publicError(error), { usage, blocker: publicError(error) }); else await this.transition(current, "BLOCKED", "BLOCKED", publicError(error), { usage, blocker: publicError(error) }); } } finally { clearTimeout(timer); if (this.active.get(id) === controller) this.active.delete(id); this.changed(); this.schedulePump(); }
  }
  private async progress(id: string, attempt: number, state: "WAITING_TOOL" | "RUNNING", detail?: string, checkpointDraft?: { summary: string; opaqueState: string }) { const current = await this.store.get(id); if (!current || current.usage.attempts !== attempt || !((current.status === "RUNNING" && state === "WAITING_TOOL") || (current.status === "WAITING_TOOL" && state === "RUNNING"))) return false; const invalid = await this.revalidate(current); if (invalid) { await this.cancel(id, invalid); return false; } let checkpoint = current.checkpoint; if (checkpointDraft) { const draft = { schemaVersion: 1 as const, attempt, summary: redactInvestigationText(checkpointDraft.summary).slice(0, 2_000), opaqueState: checkpointDraft.opaqueState, createdAt: this.now() }; checkpoint = { ...draft, digest: checkpointDigest(id, current.projectPathHash, draft) }; } const next = await this.transition(current, state, state === "WAITING_TOOL" ? "WAITING_TOOL" : "TOOL_RESUMED", detail || (state === "WAITING_TOOL" ? "Waiting on bounded read-only tool work." : "Read-only tool work resumed."), { checkpoint, blocker: state === "WAITING_TOOL" ? redactInvestigationText(detail || "Waiting on bounded read-only tool work.") : null }); return Boolean(next); }
  private async fail(current: InvestigationRecord, usage: InvestigationUsage, reason: string) { return this.transition(current, "FAILED", "FAILED", reason, { usage, blocker: redactInvestigationText(reason).slice(0, 2_000), completedAt: this.now() }); }
  private async transition(current: InvestigationRecord, status: InvestigationStatus, action: string, detail: string, patch: Partial<InvestigationRecord> = {}) { const next = this.next(current, status, { ...patch, updatedAt: this.now() }); const event = await this.event(next, current.status, action, detail); return await this.store.compareAndSet(current.revision, next, event) ? next : undefined; }
  private next(current: InvestigationRecord, status: InvestigationStatus, patch: Partial<InvestigationRecord>) { if (!canTransitionInvestigation(current.status, status)) throw new Error(`Illegal investigation transition ${current.status} -> ${status}.`); return { ...current, ...patch, status, revision: current.revision + 1 }; }
  private async event(record: InvestigationRecord, from: InvestigationStatus | null, action: string, detail: string) { return makeInvestigationEvent(record, (await this.store.audit(record.investigationId)).at(-1), action, from, detail, randomUUID()); }
  private async validPolicy(): Promise<InvestigationPolicy | { reason: string }> { const policy = await this.store.policy(); if (!policy?.enabled) return { reason: "Investigation policy is disabled." }; if (policy.projectPathHash !== investigationProjectHash(this.rooms.snapshot().settings.projectPath)) return { reason: "Project identity changed." }; return policy; }
  private async revalidate(record: InvestigationRecord) { const policy = await this.validPolicy(); if ("reason" in policy) return policy.reason; if (record.policyVersion !== policy.policyVersion || record.policyRevision !== policy.revision || record.projectPathHash !== policy.projectPathHash) return "Investigation authority epoch changed."; if (await this.stopped()) return "Emergency stop is active."; return null; }
  private validEvidence(refs: readonly InvestigationEvidenceRef[]) { if (!Array.isArray(refs) || refs.length > 32) return false; const snapshot = this.rooms.snapshot(); const root = path.resolve(snapshot.settings.projectPath); return refs.every((item) => { if (!item || typeof item.ref !== "string" || !item.ref.trim() || item.ref.length > 1_000) return false; if (item.kind === "room_message") return snapshot.messages.some((message) => message.id === item.ref); if (item.kind === "observability") return /^(generation|agent-health|room-activity):[A-Za-z0-9._:-]{1,200}$/.test(item.ref); if (item.kind === "project_artifact") { const resolved = path.resolve(root, item.ref); return resolved === root || resolved.startsWith(`${root}${path.sep}`); } return false; }); }
  private async archiveExpired(owner: AgentId) { const now = this.now(); for (const entry of await this.store.inbox(owner)) if ((entry.status === "UNREAD" || entry.status === "ACKNOWLEDGED") && Date.parse(entry.expiresAt) <= Date.parse(now)) await this.store.updateInbox(entry.revision, { ...entry, revision: entry.revision + 1, status: "ARCHIVED", updatedAt: now }); await this.reconcileInboxDisposition(owner); }
  private async reconcileInboxDisposition(owner: AgentId) { for (const entry of await this.store.inbox(owner)) if (entry.status === "ARCHIVED" || entry.status === "CLOSED") { const job = await this.store.get(entry.investigationId); if (job && (job.status === "COMPLETED" || job.status === "ACKNOWLEDGED")) await this.transition(job, "ARCHIVED", "INBOX_ARCHIVED", "Investigation inbox result is no longer waiting.", { resultWaiting: false }); } }
  private async stopped() { return Boolean(await this.options.emergencyStopped?.()); } private now() { return (this.options.now?.() || new Date()).toISOString(); } private changed() { this.options.onTransition?.(); } private error(error: unknown) { this.options.onError?.(error); }
}
function boundedBudget(input: Partial<InvestigationBudget> = {}, defaults = DEFAULT_INVESTIGATION_BUDGET) { const b = { ...defaults, ...input }; return Number.isSafeInteger(b.timeMs) && b.timeMs >= 1_000 && b.timeMs <= MAX_BUDGET.timeMs && Number.isSafeInteger(b.tokenLimit) && b.tokenLimit > 0 && b.tokenLimit <= MAX_BUDGET.tokenLimit && Number.isSafeInteger(b.toolCallLimit) && b.toolCallLimit > 0 && b.toolCallLimit <= MAX_BUDGET.toolCallLimit && Number.isSafeInteger(b.retryLimit) && b.retryLimit >= 0 && b.retryLimit <= MAX_BUDGET.retryLimit ? b : undefined; }
function addUsage(before: InvestigationUsage, elapsedMs: number, reported: { tokens: number; toolCalls: number }): InvestigationUsage { return { ...before, elapsedMs: before.elapsedMs + Math.max(0, Math.ceil(elapsedMs)), tokens: before.tokens + Math.max(0, Math.ceil(reported.tokens)), toolCalls: before.toolCalls + Math.max(0, Math.ceil(reported.toolCalls)) }; }
function overBudget(budget: InvestigationBudget, usage: InvestigationUsage) { return usage.elapsedMs > budget.timeMs || usage.tokens > budget.tokenLimit || usage.toolCalls > budget.toolCallLimit || usage.attempts > budget.retryLimit + 1; }
function publicError(error: unknown) { return redactInvestigationText(error instanceof Error ? error.message : String(error)).slice(0, 2_000); }
