import type express from "express";
import { isAgentId } from "../shared/participants.js";
import type { HumanPresenceRegistry } from "./human-presence.js";
import { redactInvestigationText, type InvestigationEvidenceRef } from "./investigation-record.js";
import type { InvestigationProgressChannel, InvestigationService } from "./investigation-service.js";
import type { HumanTaskSessions } from "./task-api.js";

export function projectInvestigation(job: Awaited<ReturnType<InvestigationService["list"]>>[number]) { return { investigationId: job.investigationId, revision: job.revision, owner: job.owner, objective: redactInvestigationText(job.objective), trigger: redactInvestigationText(job.trigger), signal: job.signal, evidenceRefs: job.evidenceRefs, status: job.status, budget: job.budget, usage: job.usage, providerSessionEstablished: Boolean(job.providerSessionId), checkpoint: job.checkpoint ? { attempt: job.checkpoint.attempt, summary: redactInvestigationText(job.checkpoint.summary), createdAt: job.checkpoint.createdAt } : null, resultSummary: job.resultSummary ? redactInvestigationText(job.resultSummary) : null, unresolvedQuestions: job.unresolvedQuestions, resultWaiting: job.resultWaiting, blocker: job.blocker ? redactInvestigationText(job.blocker) : null, createdAt: job.createdAt, startedAt: job.startedAt, updatedAt: job.updatedAt, completedAt: job.completedAt }; }
function send(response: express.Response, result: { kind: string; [key: string]: unknown }) { if (result.kind === "ok") return response.json(result.value); if (result.kind === "not_found") return response.status(404).json({ error: "Investigation not found." }); return response.status(result.kind === "conflict" ? 409 : 403).json(result); }
export function investigationRequestValidationError(body: unknown) { const value = body as Record<string, unknown> | null; if (!value || typeof value !== "object" || !isAgentId(value.owner) || typeof value.objective !== "string" || !value.objective.trim() || value.objective.length > 4_000 || typeof value.trigger !== "string" || !value.trigger.trim() || value.trigger.length > 1_000 || value.evidenceRefs !== undefined && !validRefs(value.evidenceRefs) || !validBudget(value.budget)) return "A bounded owner, objective, trigger, evidence list, and budget are required."; return null; }
export function registerInvestigationRoutes(input: { app: express.Express; service: InvestigationService; progressChannel?: InvestigationProgressChannel; humans: HumanPresenceRegistry; sessions: HumanTaskSessions; broadcast: () => void }) {
  const { app, service, progressChannel, humans, sessions, broadcast } = input; const human = (request: express.Request) => { const id = sessions.humanId(request.header("cookie")); return id && humans.get(id) ? id : undefined; };
  app.post("/api/investigation-executor/progress/:id/:attempt", async (request, response) => { if (!progressChannel) return response.status(404).json({ error: "Not found." }); const attempt = Number(request.params.attempt); if (!Number.isSafeInteger(attempt) || attempt < 1) return response.status(400).json({ error: "Valid attempt required." }); const result = await progressChannel.handleProgress(String(request.params.id), attempt, request.header("authorization"), request.body); return result === "accepted" ? response.status(202).json({ accepted: true }) : result === "unauthorized" ? response.status(401).json({ error: "Invalid progress authorization." }) : result === "invalid" ? response.status(400).json({ error: "Invalid bounded progress." }) : response.status(409).json({ error: "Stale investigation attempt." }); });
  app.use("/api/investigations", (request, response, next) => { const actor = human(request); if (!actor) return response.status(401).json({ error: "Join the room before managing investigations." }); response.locals.investigationActor = actor; next(); });
  app.get("/api/investigations", async (_request, response) => response.set("Cache-Control", "no-store").json({ policy: await service.policy(), jobs: (await service.list()).map(projectInvestigation) }));
  app.patch("/api/investigations/policy", async (request, response) => { const expectedRevision = Number(request.body?.expectedRevision); if (!Number.isSafeInteger(expectedRevision) || typeof request.body?.enabled !== "boolean") return response.status(400).json({ error: "expectedRevision and enabled are required." }); const result = await service.updatePolicy(expectedRevision, request.body.enabled, response.locals.investigationActor); broadcast(); return send(response, result); });
  app.post("/api/investigations", async (request, response) => { const error = investigationRequestValidationError(request.body); if (error) return response.status(400).json({ error }); const result = await service.request({ owner: request.body.owner, objective: request.body.objective, trigger: request.body.trigger, evidenceRefs: request.body.evidenceRefs, budget: request.body.budget, signal: "AUTHENTICATED_HUMAN", contextSnapshot: "Requested by an authenticated room participant." }); broadcast(); return send(response, result); });
  app.post("/api/investigations/:id/cancel", async (request, response) => { const result = await service.cancel(String(request.params.id)); broadcast(); return send(response, result); });
  app.post("/api/investigations/:id/resume", async (request, response) => { const result = await service.resume(String(request.params.id)); broadcast(); return send(response, result); });
  app.get("/api/investigations/:id/audit", async (request, response) => response.json(await service.audit(String(request.params.id))));
  app.get("/api/investigations/inbox/:owner", async (request, response) => { const owner = String(request.params.owner); if (!isAgentId(owner)) return response.status(400).json({ error: "Valid agent owner required." }); return response.json(await service.inbox(owner)); });
  app.post("/api/investigations/inbox/:id/acknowledge", async (request, response) => { const result = await service.acknowledge(String(request.params.id), request.body?.close === true); broadcast(); return send(response, result); });
}
function validRefs(value: unknown): value is InvestigationEvidenceRef[] { return Array.isArray(value) && value.length <= 32 && value.every((item) => item && typeof item === "object" && ["room_message", "project_artifact", "observability"].includes((item as InvestigationEvidenceRef).kind) && typeof (item as InvestigationEvidenceRef).ref === "string"); }
function validBudget(value: unknown) { if (value === undefined) return true; if (!value || typeof value !== "object" || Array.isArray(value)) return false; const budget = value as Record<string, unknown>; return Object.keys(budget).every((key) => ["timeMs", "tokenLimit", "toolCallLimit", "retryLimit"].includes(key)) && Object.values(budget).every((item) => Number.isSafeInteger(item) && Number(item) >= 0); }
