import { randomUUID } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import type express from "express";
import { afterEach, describe, expect, it, vi } from "vitest";
import { CommandRuntime } from "./command-runtime.js";
import { HumanPresenceRegistry } from "./human-presence.js";
import { HUMAN_SESSION_COOKIE, HumanSessions } from "./human-session.js";
import type { ProjectRepositoryConnection } from "./project-repository-connection.js";
import { ServerHeldRepositoryCredentials } from "./project-repository-connection.js";
import { RoomBoundGitHubReadService } from "./room-bound-github-read.js";
import { RoomCommandDispatcher } from "./room-command-dispatcher.js";
import { registerRoomLifecycleRoutes } from "./room-lifecycle-api.js";
import { RoomLifecycleStore } from "./room-lifecycle.js";
import { RoomRuntimeRegistry } from "./room-runtime-registry.js";
import type { IdentityRepository } from "./storage/identity-domain.js";
import type { RoomRepository } from "./storage/room-repository.js";
import { SqliteRoomRepository } from "./storage/sqlite-room-repository.js";

const roots:string[]=[];afterEach(async()=>Promise.all(roots.splice(0).map((root)=>rm(root,{recursive:true,force:true}))));
const sha="0123456789abcdef0123456789abcdef01234567";
function connection(projectId:string,id:string,repository:string,credentialReference:string):ProjectRepositoryConnection{return{schemaVersion:1,connectionId:id,projectId,revision:1,state:"verified",remote:{provider:"github",owner:"owner",repository,canonical:`github.com/owner/${repository}`},checkoutMode:"existing-local",checkoutPath:`/repos/${projectId}`,commonDirectory:`/repos/${projectId}/.git`,defaultBranch:"main",protectedBranches:["main"],policyRevision:1,worktreeRoot:`/worktrees/${projectId}`,validationCommands:[],sensitivePaths:[],credentialReference,identityDigest:"a".repeat(64),validatedAt:"2026-08-28T00:00:00.000Z",disabledAt:null,createdAt:"2026-08-28T00:00:00.000Z",updatedAt:"2026-08-28T00:00:00.000Z"};}
type Handler=(request:express.Request,response:express.Response)=>unknown;

async function fixture(){
  const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-room-gh-api-"));roots.push(root);const databasePath=path.join(root,"state.sqlite");const canonical=await SqliteRoomRepository.open(root,databasePath);canonical.close();
  const database=new DatabaseSync(databasePath,{enableForeignKeyConstraints:true});const server=database.prepare("SELECT server_id FROM durable_servers LIMIT 1").get() as {server_id:string};const now=new Date().toISOString();const projectOne=randomUUID(),projectTwo=randomUUID();for(const [id,name] of [[projectOne,"One"],[projectTwo,"Two"]])database.prepare("INSERT INTO durable_projects(project_id,server_id,revision,name,repository_capacity,repository_reference_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").run(id,server.server_id,1,name,1,null,now,now);database.close();
  const lifecycle=await RoomLifecycleStore.open(databasePath,root);const humans=new HumanPresenceRegistry(),sessions=new HumanSessions();const human=humans.join({name:"Ada"});const roomA=lifecycle.create(human.id,{name:"A",projectId:projectOne}),roomB=lifecycle.create(human.id,{name:"B",projectId:projectOne}),roomC=lifecycle.create(human.id,{name:"C",projectId:projectTwo}),general=lifecycle.create(human.id,{name:"General"});
  const runtimes=new RoomRuntimeRegistry((roomId)=>SqliteRoomRepository.open(root,databasePath,{roomId}),{perRoomLimit:2,globalLimit:4,providerLimits:{},dormantAfterMs:100});const records=new Map<string,ProjectRepositoryConnection>([[projectOne,connection(projectOne,"connection-one","one","credential-one")],[projectTwo,connection(projectTwo,"connection-two","two","credential-two")]]);const credentials=new ServerHeldRepositoryCredentials();credentials.register(projectOne,"credential-one","secret-one");credentials.register(projectTwo,"credential-two","secret-two");
  const fetcher=vi.fn(async(input:string|URL)=>{const url=new URL(input);const number=Number(url.pathname.split("/").at(-1));return new Response(JSON.stringify({number,title:`Result for ${url.pathname}`,state:"open",draft:false,user:{login:"author"},updated_at:now,base:{ref:"main"},head:{ref:"branch",sha},body:"safe"}),{status:200,headers:{"content-type":"application/json"}});});
  const github=new RoomBoundGitHubReadService(async(roomId)=>(await runtimes.acquire(roomId)).repository as RoomRepository&IdentityRepository,(projectId)=>({inspectServer:()=>records.get(projectId),revalidateAuthority:async(revision:number)=>{const current=records.get(projectId);return current&&current.revision===revision?{kind:"ok" as const,connection:structuredClone(current)}:{kind:"rejected" as const,reason:"Repository connection revision is stale."};}}) as never,credentials,{fetcher});let failPublication=false;
  const commands=new RoomCommandDispatcher(async(room)=>new CommandRuntime({store:room.repository,roomId:room.roomId,ceiling:["help","gh"],roster:()=>room.repository.snapshot().roster!,canLaunch:()=>false,executeTask:async()=>({}),executePov:async()=>({}),deliverPov:async()=>undefined,deliverTask:async()=>undefined,publishStatus:async(id,text)=>{await room.repository.addCommandAuditMessageOnce(id,text);},githubRead:github,publishGhResult:async(id,text)=>{if(failPublication)throw new Error("controlled outbox failure");await room.repository.addCommandDeliveryMessageOnce(id,0,"system",text);}}));
  const handlers=new Map<string,Handler>();const app={} as express.Express;for(const method of ["get","post","patch","put"] as const)(app[method] as unknown)=(route:string,handler:Handler)=>{handlers.set(`${method}:${route}`,handler);return app;};registerRoomLifecycleRoutes({app,lifecycle,runtimes,humans,sessions,commands});
  const call=async(method:"get"|"post",route:string,roomId:string,body:unknown={})=>{let status=200,payload:unknown;const request={params:{roomId},body,query:{},header:(name:string)=>name.toLowerCase()==="cookie"?`${HUMAN_SESSION_COOKIE}=${sessions.issue(human.id)}`:undefined} as unknown as express.Request;const response={status:(value:number)=>{status=value;return response;},set:()=>response,json:(value:unknown)=>{payload=value;return response;}} as unknown as express.Response;await handlers.get(`${method}:${route}`)!(request,response);return{status,payload};};
  return{call,fetcher,databasePath,rooms:{roomA,roomB,roomC,general},runtimes,commands,lifecycle,setFailPublication:(value:boolean)=>{failPublication=value;},close:async()=>{await commands.close();runtimes.close();lifecycle.close();}};
}

describe("real lifecycle room GitHub command routing",()=>{
  it("binds human slash commands to exact member rooms, shares only authorized scopes, and never stores raw slash text",async()=>{const f=await fixture();const route="/api/rooms/:roomId/messages";const state="/api/rooms/:roomId/state";
    expect((await f.call("post",route,f.rooms.roomA.roomId,{text:"/gh pr 98",clientMessageId:"room-a-gh-0001"})).status).toBe(202);expect(f.fetcher).toHaveBeenCalledTimes(1);
    expect((await f.call("post",route,f.rooms.roomB.roomId,{text:"/gh pr 98",clientMessageId:"room-b-gh-0001"})).status).toBe(202);expect(f.fetcher).toHaveBeenCalledTimes(1);
    expect((await f.call("post",route,f.rooms.roomC.roomId,{text:"/gh pr 98",clientMessageId:"room-c-gh-0001"})).status).toBe(202);expect(f.fetcher).toHaveBeenCalledTimes(2);
    const denied=await f.call("post",route,f.rooms.general.roomId,{text:"/gh pr 98",clientMessageId:"room-general-gh-01"});expect(denied).toMatchObject({status:400,payload:{command:true,result:{kind:"private-error",message:"This room is not attached to a project."}}});expect(f.fetcher).toHaveBeenCalledTimes(2);
    for(const room of Object.values(f.rooms)){const snapshot=await f.call("get",state,room.roomId);const messages=(snapshot.payload as {messages:Array<{text:string}>}).messages;expect(messages.some(({text})=>text==="/gh pr 98"||text.includes("pr 98"))).toBe(false);}const database=new DatabaseSync(f.databasePath);for(const [clientSubmissionId,roomId] of [["room-a-gh-0001",f.rooms.roomA.roomId],["room-b-gh-0001",f.rooms.roomB.roomId],["room-c-gh-0001",f.rooms.roomC.roomId]]){const submission=database.prepare("SELECT submission_id,room_id FROM command_submissions WHERE client_submission_id=?").get(clientSubmissionId) as {submission_id:string;room_id:string};expect(submission.room_id).toBe(roomId);expect((database.prepare("SELECT room_id FROM command_gh_executions WHERE submission_id=?").get(submission.submission_id) as {room_id:string}).room_id).toBe(roomId);expect((database.prepare("SELECT room_id FROM command_audit_identities WHERE submission_id=?").get(submission.submission_id) as {room_id:string}).room_id).toBe(roomId);}expect(database.prepare("SELECT COUNT(*) AS count FROM command_submissions WHERE client_submission_id='room-general-gh-01'").get()).toEqual({count:0});for(const row of database.prepare("SELECT room_id,text FROM messages WHERE text LIKE 'GitHub %' OR id LIKE 'command-audit:%'").all() as Array<{room_id:string;text:string}>)expect([f.rooms.roomA.roomId,f.rooms.roomB.roomId,f.rooms.roomC.roomId]).toContain(row.room_id);database.close();expect(f.commands.inspect()).toEqual({activeRooms:0});await f.close();
  });

  it("isolates replay and recovers a room-local delivery outbox without refetching or duplicate publication",async()=>{const f=await fixture();const route="/api/rooms/:roomId/messages",state="/api/rooms/:roomId/state";f.setFailPublication(true);const first=await f.call("post",route,f.rooms.roomA.roomId,{text:"/gh pr 98",clientMessageId:"room-a-outbox-01"});expect(first.status).toBe(202);expect(f.fetcher).toHaveBeenCalledTimes(1);f.setFailPublication(false);const replay=await f.call("post",route,f.rooms.roomA.roomId,{text:"/gh pr 98",clientMessageId:"room-a-outbox-01"});expect(replay).toMatchObject({status:200,payload:{result:{kind:"accepted",duplicate:true}}});expect(f.fetcher).toHaveBeenCalledTimes(1);const a=await f.call("get",state,f.rooms.roomA.roomId),b=await f.call("get",state,f.rooms.roomB.roomId);expect((a.payload as {messages:Array<{text:string}>}).messages.filter(({text})=>text.startsWith("GitHub PR #98"))).toHaveLength(1);expect((b.payload as {messages:Array<{text:string}>}).messages.some(({text})=>text.startsWith("GitHub PR #98"))).toBe(false);expect(JSON.stringify(a.payload)).not.toContain("/gh pr 98");expect(f.commands.inspect()).toEqual({activeRooms:0});await f.close();});
});
