import { describe, expect, it, vi } from "vitest";
import { RoomGenerationCapacity, RoomRuntimeRegistry } from "./room-runtime-registry.js";
import type { RoomRepository } from "./storage/room-repository.js";

const repository=()=>({close:vi.fn(),snapshot:()=>({messages:[],sessions:{},settings:{},status:"idle"})}) as unknown as RoomRepository&{close:ReturnType<typeof vi.fn>};
describe("room runtime registry",()=>{
  it("opens each room once under concurrency and enforces room, global, and provider caps independently",async()=>{const repos=new Map<string,ReturnType<typeof repository>>();const open=vi.fn(async(id:string)=>{const value=repository();repos.set(id,value);return value;});const registry=new RoomRuntimeRegistry(open,{perRoomLimit:2,globalLimit:3,providerLimits:{openai:2},dormantAfterMs:100});const [a1,a2,b]=await Promise.all([registry.acquire("a"),registry.acquire("a"),registry.acquire("b")]);expect(a1).toBe(a2);expect(open).toHaveBeenCalledTimes(2);const l1=registry.reserve(a1,"a-1","codex-sol","openai")!,l2=registry.reserve(a1,"a-2","claude-sonnet","openai")!;expect(registry.reserve(a1,"a-3","cursor-grok","other")).toBeUndefined();expect(registry.reserve(b,"b-1","cursor-grok","openai")).toBeUndefined();const l3=registry.reserve(b,"b-2","cursor-grok","other")!;expect(registry.snapshot()).toMatchObject({globalActive:3,providerActive:{openai:2,other:1}});l1.release();expect(registry.reserve(b,"b-3","cursor-composer","openai")).toBeTruthy();l2.release();l3.release();registry.close();});
  it("does not retain a runtime per durable room and lazily releases only dormant inactive resources",async()=>{let now=0;const repositories:ReturnType<typeof repository>[]=[];const registry=new RoomRuntimeRegistry(async()=>{const value=repository();repositories.push(value);return value;},{perRoomLimit:1,globalLimit:2,providerLimits:{},dormantAfterMs:50,now:()=>now});for(let index=0;index<2_000;index+=1){await registry.acquire(`room-${index}`);now+=51;registry.releaseDormant();}expect(registry.snapshot().runtimeCount).toBe(0);expect(repositories.every((value)=>value.close.mock.calls.length===1)).toBe(true);registry.close();});
  it("combines canonical and lifecycle room launches under the same global and provider ceilings",async()=>{const capacity=new RoomGenerationCapacity({perRoomLimit:2,globalLimit:2,providerLimits:{openai:1}});const registry=new RoomRuntimeRegistry(async()=>repository(),{perRoomLimit:2,globalLimit:2,providerLimits:{openai:1},dormantAfterMs:100},capacity);const alternate=await registry.acquire("alternate");const canonical=capacity.reserve("canonical","openai")!;expect(registry.reserve(alternate,"alternate-openai","codex-sol","openai")).toBeUndefined();const other=registry.reserve(alternate,"alternate-other","claude-sonnet","anthropic")!;expect(capacity.reserve("canonical","anthropic")).toBeUndefined();canonical.release();expect(registry.reserve(alternate,"alternate-openai","codex-sol","openai")).toBeTruthy();other.release();registry.close();});
});
