import type express from "express";
import type { HumanPresenceRegistry } from "./human-presence.js";
import { sessionHuman, type HumanSessions } from "./human-session.js";
import type { RoomLifecycleStore } from "./room-lifecycle.js";
import type { RoomRuntimeRegistry } from "./room-runtime-registry.js";
import type { RoomCommandDispatcher } from "./room-command-dispatcher.js";
import { sendCommandResponse } from "./command-api.js";
import type { PublicRoomState } from "./types.js";
import type { RoomState } from "./types.js";

const forbiddenAuthorityKeys=new Set(["humanId","participantId","actorId","memberId","developerRole","repositoryReferenceId","credential","providerSessionId"]);
function hasAuthorityInput(value:unknown,depth=0):boolean{
  if(!value||typeof value!=="object"||depth>4)return false;
  if(Array.isArray(value))return value.some((item)=>hasAuthorityInput(item,depth+1));
  return Object.entries(value as Record<string,unknown>).some(([key,item])=>forbiddenAuthorityKeys.has(key)||hasAuthorityInput(item,depth+1));
}

export function registerRoomLifecycleRoutes(input:{app:express.Express;lifecycle:RoomLifecycleStore;runtimes:RoomRuntimeRegistry;humans:HumanPresenceRegistry;sessions:HumanSessions;commands?:RoomCommandDispatcher}){
  const {app,lifecycle,runtimes,humans,sessions,commands}=input;
  const actor=(request:express.Request,response:express.Response)=>{const human=sessionHuman(request,humans,sessions);if(!human)response.status(401).json({error:"Join a room before accessing rooms."});return human;};
  const failure=(response:express.Response,error:unknown)=>{const message=error instanceof Error?error.message:"Room operation failed.";const status=/not found/i.test(message)?404:/revision/i.test(message)?409:/locked|read-only/i.test(message)?409:400;return response.status(status).json({error:message});};
  app.get("/api/rooms",(request,response)=>{const human=actor(request,response);if(human)response.set("Cache-Control","no-store").json({items:lifecycle.list(human.id,request.query.archived==="true")});});
  app.post("/api/rooms",(request,response)=>{const human=actor(request,response);if(!human)return;if(hasAuthorityInput(request.body))return response.status(400).json({error:"Caller-selected participant authority is not accepted."});try{return response.status(201).json(lifecycle.create(human.id,request.body||{}));}catch(error){return failure(response,error);}});
  app.get("/api/rooms/:roomId",(request,response)=>{const human=actor(request,response);if(!human)return;const room=lifecycle.read(request.params.roomId,human.id);return room?response.set("Cache-Control","no-store").json(room):response.status(404).json({error:"Room not found."});});
  app.patch("/api/rooms/:roomId",(request,response)=>{const human=actor(request,response);if(!human)return;if(hasAuthorityInput(request.body))return response.status(400).json({error:"Caller-selected participant authority is not accepted."});try{return response.json(lifecycle.update(request.params.roomId,human.id,request.body?.expectedRevision,request.body||{}));}catch(error){return failure(response,error);}});
  app.post("/api/rooms/:roomId/archive",(request,response)=>{const human=actor(request,response);if(!human)return;try{return response.json(lifecycle.archive(request.params.roomId,human.id,request.body?.expectedRevision));}catch(error){return failure(response,error);}});
  app.post("/api/rooms/:roomId/fork",(request,response)=>{const human=actor(request,response);if(!human)return;if(hasAuthorityInput(request.body))return response.status(400).json({error:"Caller-selected participant authority is not accepted."});try{return response.status(201).json(lifecycle.fork(request.params.roomId,human.id,request.body||{}));}catch(error){return failure(response,error);}});
  app.put("/api/rooms/:roomId/project-attachment",(request,response)=>{const human=actor(request,response);if(!human)return;if(hasAuthorityInput(request.body))return response.status(400).json({error:"Caller-selected participant authority is not accepted."});const projectId=request.body?.projectId===null?null:typeof request.body?.projectId==="string"?request.body.projectId:null;try{return response.json(lifecycle.attach(request.params.roomId,human.id,request.body?.expectedRevision,projectId));}catch(error){return failure(response,error);}});
  app.get("/api/rooms/:roomId/project-attachment/events",(request,response)=>{const human=actor(request,response);if(!human)return;try{return response.set("Cache-Control","no-store").json({items:lifecycle.attachmentHistory(request.params.roomId,human.id)});}catch(error){return failure(response,error);}});

  app.get("/api/rooms/:roomId/state",async(request,response)=>{const human=actor(request,response);if(!human)return;const room=lifecycle.read(request.params.roomId,human.id);if(!room)return response.status(404).json({error:"Room not found."});try{const runtime=await runtimes.acquire(room.roomId);return response.set("Cache-Control","no-store").json(publicState(runtime,human.id,room));}catch(error){return failure(response,error);}});
  app.post("/api/rooms/:roomId/messages",async(request,response)=>{const human=actor(request,response);if(!human)return;const room=lifecycle.read(request.params.roomId,human.id);if(!room)return response.status(404).json({error:"Room not found."});if(room.archivedAt)return response.status(409).json({error:"Archived rooms are read-only."});if(hasAuthorityInput(request.body))return response.status(400).json({error:"Caller-selected participant authority is not accepted."});const text=typeof request.body?.text==="string"?request.body.text.trim().slice(0,20_000):"";if(!text)return response.status(400).json({error:"Message text is required."});try{const runtime=await runtimes.acquire(room.roomId);const clientMessageId=typeof request.body?.clientMessageId==="string"?request.body.clientMessageId.trim():"";if(text.startsWith("/")){if(!commands)return response.status(400).set("Cache-Control","no-store").json({error:"Room commands are not configured.",kind:"private-error"});const result=await commands.submit(runtime,text,{kind:"human",id:human.id,displayName:human.name},clientMessageId);for(const [viewerId,stream] of runtime.events)stream.broadcast(publicState(runtime,viewerId,room));return sendCommandResponse(response,result,clientMessageId);}const duplicate=clientMessageId?runtime.repository.snapshot().messages.find((candidate)=>candidate.humanId===human.id&&candidate.clientMessageId===clientMessageId):undefined;if(duplicate)return response.json({accepted:true,duplicate:true,clientMessageId,messageId:duplicate.id});const message=await runtime.repository.addMessage("you",text,"chat",undefined,undefined,{id:human.id,name:human.name,clientMessageId});for(const [viewerId,stream] of runtime.events)stream.broadcast(publicState(runtime,viewerId,room));return response.status(201).json({accepted:true,duplicate:false,clientMessageId:message.clientMessageId,messageId:message.id});}catch(error){return failure(response,error);}});
  app.get("/api/rooms/:roomId/events",async(request,response)=>{const human=actor(request,response);if(!human)return;const room=lifecycle.read(request.params.roomId,human.id);if(!room)return response.status(404).json({error:"Room not found."});try{const runtime=await runtimes.acquire(room.roomId);runtime.clients+=1;const present=runtime.presence.get(human.id);runtime.presence.set(human.id,{human,connections:(present?.connections||0)+1});const stream=runtimes.stream(runtime,human.id);stream.connect(request,response,publicState(runtime,human.id,room),()=>{runtime.clients=Math.max(0,runtime.clients-1);const current=runtime.presence.get(human.id);if(current&&current.connections>1)runtime.presence.set(human.id,{...current,connections:current.connections-1});else runtime.presence.delete(human.id);runtime.lastUsedAt=Date.now();for(const [viewerId,candidate] of runtime.events)candidate.broadcast(publicState(runtime,viewerId,room));});for(const [viewerId,candidate] of runtime.events)candidate.broadcast(publicState(runtime,viewerId,room));}catch(error){return failure(response,error);}});
}

function publicState(runtime:import("./room-runtime-registry.js").RoomRuntime,humanId:string,room:ReturnType<RoomLifecycleStore["read"]>):PublicRoomState&{room:NonNullable<typeof room>}{
  const state:RoomState=runtime.repository.snapshot();
  const {sessions:_sessions,error:_error,agentContextSummaries:_summaries,roomConfigurationAudit:_audit,...rest}=state;
  return {...rest,humans:[...runtime.presence.values()].map(({human})=>human),activeGenerations:Object.fromEntries([...runtime.activeGenerations].map(([generationId,{agent}])=>[generationId,agent])),messages:state.messages.filter((message)=>!message.recipientHumanId||message.recipientHumanId===humanId).map(({recipientHumanId:_,...message})=>message),settings:{roomName:state.settings.roomName,topic:state.settings.topic,conversationEnergy:state.settings.conversationEnergy,participantStyles:state.settings.participantStyles},room:room!};
}
