import { spawn, type ChildProcess } from "node:child_process";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import net from "node:net";
import path from "node:path";
import { InvestigationStore } from "../server/investigation-store.js";

interface HttpResult<T = any> { status: number; body: T; text: string }
interface ManagedProcess { name: string; child: ChildProcess; output: string[] }
interface StepResult { name: string; status: "passed" | "failed"; durationMs: number; detail?: string }

const projectRoot = process.cwd(); const runId = new Date().toISOString().replace(/[:.]/g, "-"); const runRoot = path.join(projectRoot, ".runtime", "investigation-canary", runId); const dataDirectory = path.join(runRoot, "state"); const canaryProject = path.join(runRoot, "project"); const worktrees = path.join(runRoot, "assignment-worktrees"); const reportPath = path.join(runRoot, "report.json");
const steps: StepResult[] = []; const processes: ManagedProcess[] = []; let room: ManagedProcess | undefined; let executor: ManagedProcess | undefined; let cookie = ""; let humanId = "";

function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
async function freePort() { return new Promise<number>((resolve, reject) => { const server = net.createServer(); server.once("error", reject); server.listen(0, "127.0.0.1", () => { const address = server.address(); const port = typeof address === "object" && address ? address.port : 0; server.close((error) => error ? reject(error) : resolve(port)); }); }); }
async function http<T = any>(base: string, route: string, input: { method?: string; body?: unknown; cookie?: string; expected?: number | number[] } = {}): Promise<HttpResult<T>> { const response = await fetch(`${base}${route}`, { method: input.method || "GET", headers: { ...(input.body !== undefined ? { "content-type": "application/json" } : {}), ...(input.cookie ? { cookie: input.cookie } : {}) }, body: input.body === undefined ? undefined : JSON.stringify(input.body) }); const text = await response.text(); let body: any = null; try { body = text ? JSON.parse(text) : null; } catch { body = text; } const expected = Array.isArray(input.expected) ? input.expected : [input.expected ?? 200]; if (!expected.includes(response.status)) throw new Error(`${input.method || "GET"} ${route} returned ${response.status}, expected ${expected.join("/")}: ${text}`); return { status: response.status, body, text }; }
async function eventually<T>(operation: () => Promise<T | undefined | false>, timeoutMs = 8_000): Promise<T> { const deadline = Date.now() + timeoutMs; let latest: T | undefined | false; while (Date.now() < deadline) { latest = await operation(); if (latest) return latest; await new Promise((resolve) => setTimeout(resolve, 50)); } throw new Error(`Timed out after ${timeoutMs}ms; latest=${JSON.stringify(latest)}`); }
async function step(name: string, operation: () => Promise<string | void>) { const started = Date.now(); try { const detail = await operation(); steps.push({ name, status: "passed", durationMs: Date.now() - started, ...(detail ? { detail } : {}) }); process.stdout.write(`PASS ${name}${detail ? ` — ${detail}` : ""}\n`); } catch (error) { const detail = error instanceof Error ? error.message : String(error); steps.push({ name, status: "failed", durationMs: Date.now() - started, detail }); process.stdout.write(`FAIL ${name} — ${detail}\n`); throw error; } }
function controlledEnvironment(overrides: NodeJS.ProcessEnv) { const base = Object.fromEntries(Object.entries(process.env).filter(([name]) => !name.startsWith("ALL_MY_FRIENDS_ARE_AGENTS_") && !name.startsWith("AGENTWIRE_") && name !== "DATABASE_URL")); return { ...base, ...overrides }; }
function start(name: string, file: string, environment: NodeJS.ProcessEnv) { const output: string[] = []; const child = spawn(process.execPath, ["--import", "tsx", file], { cwd: projectRoot, env: environment, stdio: ["ignore", "pipe", "pipe"] }); const record = { name, child, output }; processes.push(record); child.stdout?.on("data", (chunk) => output.push(String(chunk))); child.stderr?.on("data", (chunk) => output.push(String(chunk))); return record; }
async function stop(record: ManagedProcess | undefined) { if (!record || record.child.exitCode !== null) return; record.child.kill("SIGTERM"); await Promise.race([new Promise<void>((resolve) => record.child.once("exit", () => resolve())), new Promise<void>((resolve) => setTimeout(resolve, 5_000))]); if (record.child.exitCode === null) { record.child.kill("SIGKILL"); await new Promise<void>((resolve) => record.child.once("exit", () => resolve())); } }

let roomPort = 0; let executorPort = 0; let roomBase = ""; let executorBase = "";
function startRoom(configuredProject = canaryProject) { room = start("room", path.join(projectRoot, "server", "index.ts"), controlledEnvironment({ ALL_MY_FRIENDS_ARE_AGENTS_HOST: "127.0.0.1", ALL_MY_FRIENDS_ARE_AGENTS_PORT: String(roomPort), ALL_MY_FRIENDS_ARE_AGENTS_STORAGE_BACKEND: "json", ALL_MY_FRIENDS_ARE_AGENTS_DATA_DIR: dataDirectory, ALL_MY_FRIENDS_ARE_AGENTS_PROJECT_PATH: configuredProject, ALL_MY_FRIENDS_ARE_AGENTS_ASSIGNMENT_WORKTREES_DIR: worktrees, ALL_MY_FRIENDS_ARE_AGENTS_INVESTIGATIONS_ENABLED: "false", ALL_MY_FRIENDS_ARE_AGENTS_INVESTIGATION_CONCURRENCY: "1", ALL_MY_FRIENDS_ARE_AGENTS_INVESTIGATION_EXECUTOR_URL: `${executorBase}/v1/investigations`, ALL_MY_FRIENDS_ARE_AGENTS_INVESTIGATION_PROGRESS_BASE_URL: roomBase })); return eventually(async () => { try { return (await http(roomBase, "/api/ready")).body.ready === true ? true : undefined; } catch { if (room?.child.exitCode !== null) throw new Error(`Room exited early:\n${room?.output.join("")}`); return undefined; } }, 12_000); }
async function join() { const response = await fetch(`${roomBase}/api/humans`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Investigation Canary" }) }); if (response.status !== 201) throw new Error(`Join returned ${response.status}: ${await response.text()}`); cookie = response.headers.get("set-cookie")?.split(";")[0] || ""; const body = await response.json() as { id: string }; humanId = body.id; assert(cookie && humanId, "Join did not issue a bound human session."); }
async function dashboard() { return (await http<any>(roomBase, "/api/investigations", { cookie })).body; }
async function executorState() { return (await http<any>(executorBase, "/control/state")).body; }
async function mode(value: string) { await http(executorBase, "/control/mode", { method: "POST", body: { mode: value } }); }
async function create(owner: string, objective: string, extra: Record<string, unknown> = {}) { return (await http<any>(roomBase, "/api/investigations", { method: "POST", cookie, body: { owner, objective, trigger: `Canary trigger for ${objective}`, ...extra } })).body; }
async function job(id: string, status?: string) { return eventually(async () => { const found = (await dashboard()).jobs.find((candidate: any) => candidate.investigationId === id); return found && (!status || found.status === status) ? found : undefined; }); }

async function main() {
  await mkdir(dataDirectory, { recursive: true }); await mkdir(canaryProject, { recursive: true }); await mkdir(worktrees, { recursive: true }); await writeFile(path.join(canaryProject, "README.md"), "Disposable investigation canary project.\n"); roomPort = await freePort(); executorPort = await freePort(); roomBase = `http://127.0.0.1:${roomPort}`; executorBase = `http://127.0.0.1:${executorPort}`;
  executor = start("executor", path.join(projectRoot, "scripts", "investigation-canary-executor.ts"), controlledEnvironment({ AMFAA_CANARY_EXECUTOR_PORT: String(executorPort) })); await eventually(async () => { try { return (await http(executorBase, "/health")).body.ready ? true : undefined; } catch { if (executor?.child.exitCode !== null) throw new Error(`Executor exited early:\n${executor?.output.join("")}`); return undefined; } }); await startRoom(); await join();

  await step("default-off and unauthenticated launch gate", async () => { const unauthenticated = await Promise.all(Array.from({ length: 8 }, () => http(roomBase, "/api/investigations", { method: "POST", body: { owner: "codex-sol", objective: "flood", trigger: "forged" }, expected: 401 }))); assert(unauthenticated.every((item) => item.status === 401), "Unauthenticated flood was not uniformly rejected."); await http(roomBase, "/api/investigations", { method: "POST", cookie, body: { owner: "codex-sol", objective: "disabled", trigger: "canary" }, expected: 403 }); assert((await executorState()).dispatches.length === 0, "Default-off requests reached the executor."); const current = await dashboard(); await http(roomBase, "/api/investigations/policy", { method: "PATCH", cookie, body: { expectedRevision: current.policy.revision, enabled: true } }); return "8 forged requests rejected; zero dispatches"; });
  await step("evidence confinement and public projection", async () => { await http(roomBase, "/api/investigations", { method: "POST", cookie, body: { owner: "codex-sol", objective: "escape", trigger: "canary", evidenceRefs: [{ kind: "project_artifact", ref: "/etc/passwd" }] }, expected: 403 }); const current = await dashboard(); const serialized = JSON.stringify(current); assert(!/projectPathHash|updatedBy|opaqueState|providerSessionId|contextSnapshot|READ_PROJECT/.test(serialized), "Dashboard leaked an internal investigation field."); return "path escape rejected; internal fields absent"; });
  await step("successful inbox-only completion and closure", async () => { await mode("success"); const created = await create("codex-sol", "happy path"); assert(!/projectPathHash|updatedBy|opaqueState|providerSessionId|contextSnapshot|READ_PROJECT/.test(JSON.stringify(created)), "Create response leaked an internal investigation field."); const completed = await job(created.investigationId, "COMPLETED"); assert(completed.providerSessionEstablished, "Completed job did not establish an isolated session."); const inbox = (await http<any[]>(roomBase, "/api/investigations/inbox/codex-sol", { cookie })).body; const entry = inbox.find((candidate) => candidate.investigationId === created.investigationId); assert(entry, "Completed result did not enter the inbox."); const state = (await http<any>(roomBase, "/api/state")).body; assert(!state.messages.some((message: any) => String(message.text).includes("Canary result")), "Investigation result posted into the transcript."); const executorDispatch = (await executorState()).dispatches.find((candidate: any) => candidate.investigationId === created.investigationId); assert(JSON.stringify(executorDispatch.capabilities) === JSON.stringify(["READ_PROJECT", "READ_OBSERVABILITY", "RUN_READ_ONLY_TESTS"]), "Executor received unexpected capabilities."); assert(["TASK_AUTHORITY", "EDIT", "EXTERNAL_REQUEST", "COMMIT", "PUSH", "MERGE", "DEPLOY", "PUBLISH"].every((capability) => executorDispatch.excludedCapabilities.includes(capability)), "Executor exclusion list is incomplete."); await http(roomBase, `/api/investigations/inbox/${encodeURIComponent(entry.inboxEntryId)}/acknowledge`, { method: "POST", cookie, body: { close: false } }); await http(roomBase, `/api/investigations/inbox/${encodeURIComponent(entry.inboxEntryId)}/acknowledge`, { method: "POST", cookie, body: { close: true } }); const closed = await job(created.investigationId, "ACKNOWLEDGED"); assert(closed.resultWaiting === false, "Closed inbox result still reports waiting."); return created.investigationId; });
  await step("global concurrency, duplicate suppression, and room-activity independence", async () => { await mode("hold"); const before = (await executorState()).dispatches.length; const first = await create("codex-sol", "held foreground independence"); const second = await create("claude-sonnet", "queued global cap"); await eventually(async () => (await executorState()).dispatches.length === before + 1 ? true : undefined); let current = await dashboard(); assert(current.jobs.find((item: any) => item.investigationId === first.investigationId)?.status === "RUNNING", "First investigation is not running."); assert(current.jobs.find((item: any) => item.investigationId === second.investigationId)?.status === "QUEUED", "Second investigation bypassed the global cap."); await http(roomBase, "/api/investigations", { method: "POST", cookie, body: { owner: "codex-sol", objective: "duplicate", trigger: "canary" }, expected: 409 }); await http(roomBase, `/api/investigation-executor/progress/${encodeURIComponent(first.investigationId)}/1`, { method: "POST", body: { state: "WAITING_TOOL" }, expected: 401 }); await http(roomBase, "/api/settings", { method: "PATCH", cookie, body: { topic: `Canary activity ${randomUUID()}` } }); current = await dashboard(); assert(current.jobs.find((item: any) => item.investigationId === first.investigationId)?.status === "RUNNING", "Room activity cancelled the investigation lane."); await http(executorBase, "/control/release", { method: "POST", body: {} }); await job(first.investigationId, "COMPLETED"); await eventually(async () => (await executorState()).dispatches.length === before + 2 ? true : undefined); await http(executorBase, "/control/release", { method: "POST", body: {} }); await job(second.investigationId, "COMPLETED"); return "cap=1 held; duplicate=409; forged callback=401"; });
  await step("durable checkpoint and restart resume", async () => { await mode("checkpoint-hold"); const created = await create("cursor-grok", "restart checkpoint"); await job(created.investigationId, "WAITING_TOOL"); await stop(room); await startRoom(); await join(); const checkpointed = await job(created.investigationId, "CHECKPOINTED"); assert(checkpointed.checkpoint?.summary === "Canary durable checkpoint", "Restart did not retain the bounded checkpoint."); await mode("success"); await http(roomBase, `/api/investigations/${encodeURIComponent(created.investigationId)}/resume`, { method: "POST", cookie, body: {} }); await job(created.investigationId, "COMPLETED"); const state = await executorState(); const resumed = state.dispatches.filter((item: any) => item.investigationId === created.investigationId).at(-1); assert(resumed.checkpoint?.summary === "Canary durable checkpoint", "Resume dispatch did not receive the durable checkpoint."); return `${created.investigationId} resumed from checkpoint`; });
  await step("uncheckpointed shutdown fails closed", async () => { await mode("hold"); const created = await create("cursor-gemini", "uncheckpointed shutdown"); await job(created.investigationId, "RUNNING"); await stop(room); await startRoom(); await join(); await job(created.investigationId, "CANCELLED"); return `${created.investigationId} cancelled on shutdown`; });
  await step("project identity change revokes checkpoint authority", async () => { await mode("checkpoint-hold"); const created = await create("cursor-composer", "project identity change"); await job(created.investigationId, "WAITING_TOOL"); await stop(room); const changedProject = path.join(runRoot, "changed-project"); await mkdir(changedProject, { recursive: true }); await startRoom(changedProject); await join(); const cancelled = await job(created.investigationId, "CANCELLED"); assert(/project/i.test(cancelled.blocker), "Project identity change did not produce a project revocation reason."); await stop(room); await startRoom(); await join(); return `${created.investigationId} cancelled after project change`; });
  await step("session collision, budget exhaustion, and provider failures", async () => { await stop(room); const roomPath = path.join(dataDirectory, "room.json"); const roomState = JSON.parse(await readFile(roomPath, "utf8")); roomState.sessions = { ...(roomState.sessions || {}), "codex-sol": { id: "canary-foreground-session", permission: "read-only" } }; await writeFile(roomPath, `${JSON.stringify(roomState, null, 2)}\n`); await startRoom(); await join(); await mode("collision"); const collision = await create("codex-sol", "session collision"); const collisionJob = await job(collision.investigationId, "FAILED"); assert(/session/i.test(collisionJob.blocker), "Session collision did not fail with a session blocker."); await mode("over-budget"); const budget = await create("codex-sol", "budget exhaustion", { budget: { tokenLimit: 1 } }); const budgetJob = await job(budget.investigationId, "FAILED"); assert(/budget/i.test(budgetJob.blocker), "Over-budget result did not fail closed."); for (const [failureMode, objective] of [["failure", "provider failure"], ["malformed", "malformed provider output"]] as const) { await mode(failureMode); const failed = await create("codex-sol", objective); await job(failed.investigationId, "BLOCKED"); await http(roomBase, `/api/investigations/${encodeURIComponent(failed.investigationId)}/cancel`, { method: "POST", cookie, body: {} }); } return "collision=FAILED; budget=FAILED; provider/malformed=BLOCKED"; });
  await step("policy revocation and emergency stop", async () => { await mode("hold"); const revoked = await create("codex-sol", "policy revocation"); await job(revoked.investigationId, "RUNNING"); const current = await dashboard(); await http(roomBase, "/api/investigations/policy", { method: "PATCH", cookie, body: { expectedRevision: current.policy.revision, enabled: true } }); await job(revoked.investigationId, "CANCELLED"); const stopped = await create("codex-sol", "emergency stop"); await job(stopped.investigationId, "RUNNING"); const heartbeat = (await http<any>(roomBase, "/api/heartbeat")).body; await http(roomBase, "/api/heartbeat/emergency-stop", { method: "POST", cookie, body: { expectedRevision: heartbeat.runtime.revision, reason: "Investigation canary emergency stop" } }); await job(stopped.investigationId, "CANCELLED"); return "both active dispatches cancelled"; });
  await stop(room); const investigationPath = path.join(dataDirectory, "investigations.json"); const durableText = await readFile(investigationPath, "utf8"); const durable = JSON.parse(durableText); assert(durable.events.length > 0 && Object.keys(durable.jobs).length >= 11, "Durable canary evidence is incomplete."); const reopened = await InvestigationStore.open(dataDirectory); assert((await reopened.list()).length === Object.keys(durable.jobs).length, "Production store validator did not reopen the complete durable projection.");
  await step("forged durable checkpoint is rejected", async () => { const checkpointed = Object.values(durable.jobs as Record<string, any>).find((candidate: any) => candidate.checkpoint); assert(checkpointed, "Canary state contains no checkpoint to tamper with."); checkpointed.checkpoint.opaqueState = "forged-canary-state"; await writeFile(investigationPath, `${JSON.stringify(durable, null, 2)}\n`); let rejected = false; try { await InvestigationStore.open(dataDirectory); } catch { rejected = true; } finally { await writeFile(investigationPath, durableText); } assert(rejected, "Production store accepted a forged checkpoint."); await InvestigationStore.open(dataDirectory); return "tamper rejected and original audit state restored"; });
}

let failure: unknown;
try { await main(); } catch (error) { failure = error; } finally { await stop(room); await stop(executor); const report = { schemaVersion: 1, runId, runRoot, branch: process.env.GIT_BRANCH || null, startedAt: runId, completedAt: new Date().toISOString(), status: failure ? "failed" : "passed", steps, processes: processes.map((record) => ({ name: record.name, exitCode: record.child.exitCode, output: record.output.join("").slice(-20_000) })) }; await mkdir(runRoot, { recursive: true }); await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`); process.stdout.write(`CANARY_REPORT ${reportPath}\n`); }
if (failure) { console.error(failure instanceof Error ? failure.stack || failure.message : failure); process.exitCode = 1; }
