import { useEffect, useState } from "react";
import { contributionGate, loadContribution, loadContributions } from "./api";

type Stage = "WORK_COMPLETED" | "REVIEW_PENDING" | "REVIEW_ACCEPTED" | "PR_PUBLISHED" | "MERGED" | "DEPLOYED" | "BLOCKED";
interface Approval { approvalId: string; kind: "PUBLICATION" | "MERGE" | "DEPLOYMENT"; consumedAt: string | null; grantedBy: string; grantedAt: string; environment: string | null; artifactDigest: string | null }
interface Contribution { contributionId: string; revision: number; stage: Stage; title: string; description: string; blockedReason: string | null; updatedAt: string;
  source: { repository: string; branch: string; baseSha: string; headSha: string; taskId: string; taskRevision: number; assignmentId: string; assignmentRevision: number; manifestRevision: number };
  review: { reviewerId: string; decision: string; summary: string; at: string } | null; pullRequest: { number: number; url: string } | null;
  merged: { commitSha: string; mergedAt: string } | null; deployed: { environment: string; commitSha: string; artifactDigest: string; deployedAt: string } | null; approvals: Approval[];
}
interface Audit { eventId: string; action: string; actorId: string; at: string; outcome: string; detail: string; externalResultId: string | null }

export function ContributionsMenuControl({ active, onOpen }: { active: boolean; onOpen: () => void }) { return <button type="button" aria-current={active ? "page" : undefined} onClick={onOpen}>Contributions</button>; }

export function Contributions({ refreshKey = 0 }: { refreshKey?: number }) {
  const [items, setItems] = useState<Contribution[]>([]); const [selected, setSelected] = useState<string | null>(null); const [detail, setDetail] = useState<{ contribution: Contribution; audit: Audit[] } | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [environment, setEnvironment] = useState("dev"); const [artifactDigest, setArtifactDigest] = useState("");
  const refresh = async () => { const [list, nextDetail] = await Promise.all([loadContributions() as Promise<{ items: Contribution[] }>, selected ? loadContribution(selected) as Promise<{ contribution: Contribution; audit: Audit[] }> : Promise.resolve(null)]); setItems(list.items); if (nextDetail) setDetail(nextDetail); };
  useEffect(() => { let cancelled = false; void loadContributions().then((value) => { if (!cancelled) setItems((value as { items: Contribution[] }).items); }).catch((reason) => { if (!cancelled) setError(reason.message); }); return () => { cancelled = true; }; }, [refreshKey]);
  useEffect(() => { if (!selected) { setDetail(null); return; } let cancelled = false; void loadContribution(selected).then((value) => { if (!cancelled) setDetail(value as { contribution: Contribution; audit: Audit[] }); }).catch((reason) => { if (!cancelled) setError(reason.message); }); return () => { cancelled = true; }; }, [selected, refreshKey]);
  useEffect(() => { const timer = window.setInterval(() => void refresh().catch(() => undefined), 5_000); return () => window.clearInterval(timer); }, [selected, refreshKey]);
  async function gate(action: "approve" | "execute", kind: "publication" | "merge" | "deployment") { if (!detail) return; setBusy(true); setError(""); setNotice(""); try {
    await contributionGate(detail.contribution.contributionId, action, kind, { expectedRevision: detail.contribution.revision, ...(kind === "deployment" && action === "approve" ? { environment, artifactDigest } : {}) }); await refresh(); setNotice(`${kind} ${action === "approve" ? "approval recorded" : "operation completed"}.`);
  } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); await refresh().catch(() => undefined); } finally { setBusy(false); } }
  return <section className="tasks-panel beveled-inset" aria-label="Reviewed contributions"><header className="tasks-header"><h2>Reviewed contributions</h2>{selected ? <button className="classic-button" onClick={() => setSelected(null)}>Back to list</button> : null}</header>
    {notice ? <div className="task-notice" role="status">{notice}</div> : null}{error ? <div className="task-error" role="alert">{error}</div> : null}<div className="tasks-body">{!selected ? (items.length ? <ul className="task-list">{items.map((item) => <li key={item.contributionId}><button onClick={() => setSelected(item.contributionId)}><strong>{item.title}</strong><span>{label(item.stage)} · revision {item.revision}</span><small>{item.source.branch} · {short(item.source.headSha)}</small></button></li>)}</ul> : <div className="task-empty"><strong>No contribution handoffs yet.</strong><span>Agents create immutable handoffs through the scoped developer API.</span></div>) : detail ? <ContributionDetail value={detail} busy={busy} environment={environment} setEnvironment={setEnvironment} artifactDigest={artifactDigest} setArtifactDigest={setArtifactDigest} gate={gate} /> : <p role="status">Loading contribution…</p>}</div>
  </section>;
}

function ContributionDetail({ value, busy, environment, setEnvironment, artifactDigest, setArtifactDigest, gate }: { value: { contribution: Contribution; audit: Audit[] }; busy: boolean; environment: string; setEnvironment: (value: string) => void; artifactDigest: string; setArtifactDigest: (value: string) => void; gate: (action: "approve" | "execute", kind: "publication" | "merge" | "deployment") => void }) {
  const item = value.contribution; const unused = (kind: Approval["kind"]) => item.approvals.some((approval) => approval.kind === kind && !approval.consumedAt);
  const steps = [{ key: "work", text: "Work completed", done: true }, { key: "review", text: "Review accepted", done: ["REVIEW_ACCEPTED", "PR_PUBLISHED", "MERGED", "DEPLOYED"].includes(item.stage) }, { key: "published", text: "PR published", done: ["PR_PUBLISHED", "MERGED", "DEPLOYED"].includes(item.stage) }, { key: "merged", text: "Merged", done: ["MERGED", "DEPLOYED"].includes(item.stage) }, { key: "deployed", text: "Deployed", done: item.stage === "DEPLOYED" }];
  return <article className="task-detail"><div className="task-state-line"><span className={`task-state task-state--${item.stage === "BLOCKED" ? "blocked" : "active"}`}>{label(item.stage)}</span><span>Revision {item.revision}</span></div><h3>{item.title}</h3><p>{item.description}</p>
    <ol className="contribution-steps">{steps.map((step) => <li key={step.key} aria-current={!step.done ? "step" : undefined} className={step.done ? "is-complete" : ""}>{step.done ? "✓" : "○"} {step.text}</li>)}</ol>{item.blockedReason ? <div className="task-error" role="alert"><strong>Blocked:</strong> {item.blockedReason}</div> : null}
    <dl className="workshop-facts"><dt>Repository</dt><dd>{item.source.repository}</dd><dt>Branch</dt><dd>{item.source.branch}</dd><dt>Base</dt><dd><code>{short(item.source.baseSha)}</code></dd><dt>Head</dt><dd><code>{short(item.source.headSha)}</code></dd><dt>Task</dt><dd>{item.source.taskId} r{item.source.taskRevision}</dd><dt>Assignment</dt><dd>{item.source.assignmentId} r{item.source.assignmentRevision} · manifest r{item.source.manifestRevision}</dd></dl>
    {item.review ? <section><h3>Independent review</h3><p><strong>{item.review.decision}</strong> by {item.review.reviewerId}: {item.review.summary}</p></section> : null}{item.pullRequest ? <p><a href={item.pullRequest.url} target="_blank" rel="noreferrer">Pull request #{item.pullRequest.number}</a></p> : null}{item.merged ? <p>Merged commit <code>{short(item.merged.commitSha)}</code></p> : null}{item.deployed ? <p>Deployed <code>{short(item.deployed.commitSha)}</code> to {item.deployed.environment}</p> : null}
    <section className="task-actions" aria-label="Exact contribution gates">{item.stage === "REVIEW_ACCEPTED" && !unused("PUBLICATION") ? <button className="classic-button" disabled={busy} onClick={() => gate("approve", "publication")}>Approve exact publication</button> : null}{item.stage === "REVIEW_ACCEPTED" && unused("PUBLICATION") ? <button className="classic-button" disabled={busy} onClick={() => gate("execute", "publication")}>Publish approved draft PR</button> : null}{item.stage === "PR_PUBLISHED" && !unused("MERGE") ? <button className="classic-button" disabled={busy} onClick={() => gate("approve", "merge")}>Approve exact merge</button> : null}{item.stage === "PR_PUBLISHED" && unused("MERGE") ? <button className="classic-button" disabled={busy} onClick={() => gate("execute", "merge")}>Merge approved commit</button> : null}</section>
    {item.stage === "MERGED" ? <section className="task-edit"><label>Environment<input value={environment} maxLength={128} onChange={(event) => setEnvironment(event.target.value)} /></label><label>Artifact SHA-256<input value={artifactDigest} maxLength={64} onChange={(event) => setArtifactDigest(event.target.value)} /></label>{!unused("DEPLOYMENT") ? <button className="classic-button" disabled={busy || !environment.trim() || !/^[0-9a-f]{64}$/.test(artifactDigest)} onClick={() => gate("approve", "deployment")}>Approve exact deployment</button> : <button className="classic-button" disabled={busy} onClick={() => gate("execute", "deployment")}>Deploy approved artifact</button>}</section> : null}
    <section><h3>Append-only audit</h3><ol className="task-history">{value.audit.map((event) => <li key={event.eventId}><strong>{event.action}</strong> · {event.outcome} · {event.actorId}<code>{event.detail}</code></li>)}</ol></section></article>;
}
function label(stage: Stage) { return ({ WORK_COMPLETED: "Work completed", REVIEW_PENDING: "Review pending", REVIEW_ACCEPTED: "Review accepted", PR_PUBLISHED: "PR published", MERGED: "Merged", DEPLOYED: "Deployed", BLOCKED: "Blocked" } as const)[stage]; }
function short(sha: string) { return sha.slice(0, 12); }
