import { validGitHubHttpDiagnostic } from "../../shared/github-http-diagnostic.js";
import { isActiveAgentId } from "../../shared/participants.js";
import { ROOM_COMMANDS } from "../../shared/command-domain.js";
import { MAX_COMMAND_DELIVERY_MESSAGE, MAX_DIAGNOSTIC_PROMPT_HEAD, MAX_DIAGNOSTIC_TEXT, type CommandAcceptance, type CommandAttempt, type CommandAuditIdentity, type CommandGhExecution, type CommandPoll, type CommandPovExecution, type CommandReassignment, type CommandSubmission, type CommandTombstone, type CommandVote, type DiagnosticRecord, type RoundRobinState } from "../command-record.js";

export interface JsonCommandState { readonly schemaVersion: 1; readonly submissions: readonly CommandSubmission[]; readonly tombstones:readonly CommandTombstone[]; readonly roundRobin: readonly RoundRobinState[]; readonly attempts: readonly CommandAttempt[]; readonly povExecutions: readonly CommandPovExecution[]; readonly ghExecutions: readonly CommandGhExecution[]; readonly polls: readonly CommandPoll[]; readonly votes: readonly CommandVote[]; readonly audits: readonly CommandAuditIdentity[]; readonly diagnostics: readonly DiagnosticRecord[] }
export function emptyJsonCommandState(): JsonCommandState { return { schemaVersion: 1, submissions: [], tombstones:[], roundRobin: [], attempts: [], povExecutions: [], ghExecutions: [], polls: [], votes: [], audits: [], diagnostics: [] }; }
const string = (value: unknown, max = 500) => typeof value === "string" && value.length > 0 && value.length <= max;
export function validSubmission(value: CommandSubmission) { return string(value?.submissionId) && string(value.roomId) && string(value.clientSubmissionId) && ROOM_COMMANDS.includes(value.command) && value.invocation?.command === value.command && string(value.invoker?.id) && string(value.invoker?.displayName) && (value.invoker?.kind === "human" || value.invoker?.kind === "agent") && string(value.createdAt); }
export function validRoundRobin(value: RoundRobinState) { return string(value?.roomId) && (value.lastAssignedAgentId === null || isActiveAgentId(value.lastAssignedAgentId)) && Number.isSafeInteger(value.revision) && value.revision >= 0 && string(value.updatedAt); }
export function validAttempt(value: CommandAttempt) { const result=value?.deliveryResult;const resultValid=result===undefined||typeof result==="object"&&(!result.sessionId||string(result.sessionId,500))&&(!result.permission||result.permission==="read-only"||result.permission==="writable")&&(!result.codeEpoch||string(result.codeEpoch,500))&&(!result.cursorMessageId||string(result.cursorMessageId,500));const deliveryValid=value?.status!=="delivery-pending"||Array.isArray(value.deliveryMessages)&&value.deliveryMessages.length<=3&&value.deliveryMessages.every((message)=>string(message,MAX_COMMAND_DELIVERY_MESSAGE))&&resultValid;return string(value?.attemptId) && string(value.roomId) && string(value.submissionId) && Number.isSafeInteger(value.attempt) && value.attempt > 0 && isActiveAgentId(value.agentId) && ["queued", "active", "delivery-pending", "completed", "failed", "superseded"].includes(value.status) && deliveryValid && string(value.createdAt) && string(value.updatedAt); }
export function validPoll(value: CommandPoll) { return string(value?.pollId) && string(value.roomId) && string(value.submissionId) && string(value.question) && Array.isArray(value.options) && value.options.length >= 2 && value.options.length <= 12 && value.options.every((option) => string(option)) && (value.creatorKind === "human" || value.creatorKind === "agent") && string(value.creatorId) && (value.state === "OPEN" || value.state === "CLOSED") && Number.isSafeInteger(value.revision) && value.revision >= 1 && (value.closedAt === null || string(value.closedAt)) && (value.closerKind === null || value.closerKind === "human" || value.closerKind === "agent" || value.closerKind === "controller") && (value.closerId === null || string(value.closerId)) && (value.closeMutationId === null || string(value.closeMutationId,100)) && (value.finalTallies === null || Array.isArray(value.finalTallies) && value.finalTallies.length === value.options.length && value.finalTallies.every((count) => Number.isSafeInteger(count) && count >= 0)) && (value.finalTotalVotes === null || Number.isSafeInteger(value.finalTotalVotes) && value.finalTotalVotes >= 0) && (value.state === "OPEN" ? value.closedAt === null && value.closerKind === null && value.closerId === null && value.closeMutationId === null && value.finalTallies === null && value.finalTotalVotes === null : Boolean(value.closedAt && value.closerKind && value.closerId && value.closeMutationId && value.finalTallies && value.finalTotalVotes === value.finalTallies.reduce((sum,count)=>sum+count,0))) && string(value.createdAt); }
export function validVote(value: CommandVote) { return string(value?.roomId) && string(value.pollId) && string(value.voterId) && string(value.mutationId,100) && Number.isSafeInteger(value.optionIndex) && value.optionIndex >= 0 && string(value.createdAt); }
export function validAudit(value: CommandAuditIdentity) { return string(value?.auditId) && string(value.roomId) && string(value.submissionId) && ROOM_COMMANDS.includes(value.command) && (value.invokerKind === "human" || value.invokerKind === "agent") && string(value.invokerId) && Array.isArray(value.targetAgentIds) && value.targetAgentIds.every(isActiveAgentId); }
export function validPovExecution(value: CommandPovExecution) { const hasOutbox=value.currentTargetAgentId!=null;const outboxValid=!hasOutbox||isActiveAgentId(value.currentTargetAgentId)&&value.targetAgentIds.includes(value.currentTargetAgentId)&&!value.processedTargetAgentIds.includes(value.currentTargetAgentId)&&Array.isArray(value.deliveryMessages)&&value.deliveryMessages.length<=3&&value.deliveryMessages.every((message)=>string(message,MAX_COMMAND_DELIVERY_MESSAGE));return string(value?.executionId) && string(value.roomId) && string(value.submissionId) && Array.isArray(value.targetAgentIds) && value.targetAgentIds.length > 0 && value.targetAgentIds.every(isActiveAgentId) && Array.isArray(value.processedTargetAgentIds) && new Set(value.processedTargetAgentIds).size===value.processedTargetAgentIds.length && value.processedTargetAgentIds.every((agent)=>isActiveAgentId(agent)&&value.targetAgentIds.includes(agent)) && outboxValid && ["queued","active","completed","failed","cancelled"].includes(value.status) && string(value.createdAt) && string(value.updatedAt); }
export function validGhExecution(value: CommandGhExecution) { return string(value?.executionId)&&string(value.roomId)&&string(value.submissionId)&&(value.authorizationLease===undefined||value.authorizationLease===null||/^sha256:[a-f0-9]{64}$|^legacy-static$/.test(value.authorizationLease))&&["queued","completed","failed"].includes(value.status)&&["pending","delivered"].includes(value.deliveryStatus)&&!(value.status==="queued"&&value.deliveryStatus!=="pending")&&Array.isArray(value.diagnostics)&&value.diagnostics.length<=8&&value.diagnostics.every((item)=>item&&validGitHubHttpDiagnostic(item))&&(value.renderedText===null||typeof value.renderedText==="string"&&value.renderedText.length<=MAX_COMMAND_DELIVERY_MESSAGE)&&(value.status==="queued"?value.projection===null&&value.renderedText===null:value.status==="completed"?Boolean(value.projection&&value.renderedText):value.projection===null&&typeof value.renderedText==="string")&&string(value.createdAt)&&string(value.updatedAt); }
export function validTombstone(value:CommandTombstone){return string(value?.roomId)&&string(value.submissionId)&&string(value.clientSubmissionId)&&ROOM_COMMANDS.includes(value.command)&&string(value.compactedAt);}
export function validDiagnostic(value: DiagnosticRecord) { return string(value?.recordId) && string(value.roomId) && isActiveAgentId(value.agentId) && string(value.attemptId) && string(value.correlationId) && string(value.promptFingerprint) && string(value.reason) && (value.promptHead === null || value.promptHead.length <= MAX_DIAGNOSTIC_PROMPT_HEAD) && (value.diagnosticText === null || value.diagnosticText.length <= MAX_DIAGNOSTIC_TEXT) && string(value.createdAt); }
export function validCommandAcceptance(value: CommandAcceptance) { const {submission,audit,poll,attempt,povExecution,ghExecution,roundRobin}=value||{} as CommandAcceptance; return validSubmission(submission)&&validAudit(audit)&&audit.roomId===submission.roomId&&audit.submissionId===submission.submissionId&&audit.command===submission.command&&(!poll||validPoll(poll)&&poll.roomId===submission.roomId&&poll.submissionId===submission.submissionId&&submission.command==="poll")&&(!attempt||validAttempt(attempt)&&attempt.roomId===submission.roomId&&attempt.submissionId===submission.submissionId&&submission.command==="task"&&attempt.attempt===1&&attempt.status==="queued")&&(!povExecution||validPovExecution(povExecution)&&povExecution.roomId===submission.roomId&&povExecution.submissionId===submission.submissionId&&submission.command==="pov"&&povExecution.status==="queued")&&(!ghExecution||validGhExecution(ghExecution)&&ghExecution.roomId===submission.roomId&&ghExecution.submissionId===submission.submissionId&&submission.command==="gh"&&ghExecution.status==="queued")&&(!roundRobin||validRoundRobin(roundRobin.state)&&roundRobin.state.roomId===submission.roomId&&roundRobin.state.revision===roundRobin.expectedRevision+1&&submission.command==="task"); }
export function validCommandReassignment(value:CommandReassignment){const{current,next,roundRobin}=value||{} as CommandReassignment;return validAttempt(current)&&validAttempt(next)&&current.status==="superseded"&&next.status==="queued"&&current.roomId===next.roomId&&current.submissionId===next.submissionId&&next.attempt===current.attempt+1&&Boolean(roundRobin)&&roundRobin.expectedRevision+1===roundRobin.state.revision&&roundRobin.state.roomId===current.roomId&&validRoundRobin(roundRobin.state)&&value.expectedUpdatedAt!==current.updatedAt;}
export function normalizeJsonCommandState(input: unknown): JsonCommandState {
  if (!input || typeof input !== "object") return emptyJsonCommandState();
  const value = input as Partial<JsonCommandState>;
  const take = <T>(candidate: unknown, validate: (entry: T) => boolean): T[] => Array.isArray(candidate) ? candidate.filter((entry): entry is T => validate(entry as T)) : [];
  const submissions = take(value.submissions, validSubmission);
  const polls = (Array.isArray(value.polls) ? value.polls : []).flatMap((candidate) => {
    const poll = candidate as Partial<CommandPoll>;
    if (poll.state === undefined) {
      const submission = submissions.find((entry) => entry.roomId === poll.roomId && entry.submissionId === poll.submissionId);
      if (!submission || submission.command !== "poll") return [];
      const migrated = { ...poll, creatorKind: submission.invoker.kind, creatorId: submission.invoker.id, state: "OPEN", revision: 1, closedAt: null, closerKind: null, closerId: null, closeMutationId: null, finalTallies: null, finalTotalVotes: null } as CommandPoll;
      return validPoll(migrated) ? [migrated] : [];
    }
    return validPoll(poll as CommandPoll) ? [poll as CommandPoll] : [];
  });
  const voterKeys = new Set<string>();
  const mutationKeys = new Set<string>();
  const votes = take(value.votes, validVote).map((vote) => /^(?:human|agent):/.test(vote.voterId) ? vote : { ...vote, voterId: `human:${vote.voterId}` })
    .filter((vote) => { const voterKey = `${vote.roomId}\0${vote.pollId}\0${vote.voterId}`; const mutationKey = `${vote.roomId}\0${vote.pollId}\0${vote.mutationId}`; if (voterKeys.has(voterKey) || mutationKeys.has(mutationKey)) return false; voterKeys.add(voterKey); mutationKeys.add(mutationKey); return true; });
  return { schemaVersion: 1, submissions, tombstones:take(value.tombstones,validTombstone), roundRobin: take(value.roundRobin, validRoundRobin), attempts: take(value.attempts, validAttempt), povExecutions: take(value.povExecutions, validPovExecution), ghExecutions: take(value.ghExecutions,validGhExecution), polls, votes, audits: take(value.audits, validAudit), diagnostics: take(value.diagnostics, validDiagnostic) };
}
