import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import type { ActiveAgentId } from "../../shared/participants.js";
import { commandPollCursor, MAX_OPEN_POLLS_PER_ROOM, type CommandSubmission } from "../command-record.js";
import { RoomStore } from "../room-store.js";
import type { RoomRepository } from "./room-repository.js";
import { DEFAULT_ROOM_ID, SqliteRoomRepository } from "./sqlite-room-repository.js";

const temporaryDirectories: string[] = [];
const factories: ReadonlyArray<readonly [string, (root: string) => Promise<{ repository: RoomRepository; reopen(): Promise<RoomRepository>; close(): void }>]> = [
  ["JSON", async (root) => { const directory = path.join(root, "json"); let repository: RoomRepository = await RoomStore.open(root, directory); return { get repository() { return repository; }, async reopen() { repository = await RoomStore.open(root, directory); return repository; }, close() {} }; }],
  ["SQLite", async (root) => { const database = path.join(root, "sqlite", "room.sqlite"); let repository: RoomRepository = await SqliteRoomRepository.open(root, database); return { get repository() { return repository; }, async reopen() { (repository as SqliteRoomRepository).close(); repository = await SqliteRoomRepository.open(root, database); return repository; }, close() { (repository as SqliteRoomRepository).close(); } }; }],
];
afterEach(async () => Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true }))));

function submission(): CommandSubmission { return { submissionId: "submission-1", roomId: DEFAULT_ROOM_ID, clientSubmissionId: "client-1", command: "poll", invocation: { command: "poll", question: "Choose", options: ["A", "B"] }, invoker: { kind: "human", id: "human-1", displayName: "Human" }, createdAt: "2026-08-27T12:00:00.000Z" }; }
const openPollLifecycle={creatorKind:"human" as const,creatorId:"human-1",state:"OPEN" as const,revision:1,closedAt:null,closerKind:null,closerId:null,closeMutationId:null,finalTallies:null,finalTotalVotes:null};

describe.each(factories)("%s command repository", (_backend, makeFixture) => {
  it("projects each accepted audit status node exactly once across replay and restart",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-contract-"));temporaryDirectories.push(root);const fixture=await makeFixture(root);try{const first=await fixture.repository.addCommandAuditMessageOnce("audit-stable","— Ada ran /task — Target: Sol");const replay=await fixture.repository.addCommandAuditMessageOnce("audit-stable","different text must not replace it");expect(replay).toEqual(first);const reopened=await fixture.reopen();expect(reopened.snapshot().messages.filter(({id})=>id==="command-audit:audit-stable")).toEqual([first]);}finally{fixture.close();}});
  it("projects command delivery messages idempotently",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-contract-"));temporaryDirectories.push(root);const fixture=await makeFixture(root);try{const first=await fixture.repository.addCommandDeliveryMessageOnce("attempt-stable",0,"codex-sol","result");expect(await fixture.repository.addCommandDeliveryMessageOnce("attempt-stable",0,"codex-sol","different")).toEqual(first);const reopened=await fixture.reopen();expect(reopened.snapshot().messages.filter(({id})=>id==="command-delivery:attempt-stable:0")).toEqual([first]);}finally{fixture.close();}});
  it("atomically accepts and persists bounded GitHub execution metadata without cache payloads",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-contract-"));temporaryDirectories.push(root);const fixture=await makeFixture(root);try{const createdAt="2026-08-27T12:00:00.000Z";const command={...submission(),command:"gh" as const,invocation:{command:"gh" as const,selector:{kind:"pr" as const,number:98}}};const audit={auditId:"gh-audit",roomId:DEFAULT_ROOM_ID,submissionId:command.submissionId,command:"gh" as const,invokerKind:"human" as const,invokerId:"human-1",targetAgentIds:[] as const,createdAt};const execution={executionId:"gh-execution",roomId:DEFAULT_ROOM_ID,submissionId:command.submissionId,status:"queued" as const,projection:null,renderedText:null,failureKind:null,diagnostics:[] as const,createdAt,updatedAt:createdAt};expect(await fixture.repository.acceptCommand({submission:command,audit,ghExecution:execution})).toMatchObject({kind:"accepted"});expect(await fixture.repository.createGhExecution(execution)).toMatchObject({kind:"duplicate"});const reopened=await fixture.reopen();const queued=await reopened.getGhExecution(DEFAULT_ROOM_ID,command.submissionId);expect(queued).toMatchObject({status:"queued",projection:null});expect(await reopened.listPendingGhExecutions(DEFAULT_ROOM_ID)).toHaveLength(1);const completed={...queued!,status:"completed" as const,projection:{kind:"pr" as const,repository:"owner/repo",pull:{number:98,title:"bounded",state:"open" as const,draft:false,author:"a",updatedAt:createdAt,base:"main",head:"branch",headSha:"0123456789abcdef0123456789abcdef01234567",merged:false,body:"safe",truncated:false}},renderedText:"GitHub PR #98 — bounded",updatedAt:"2026-08-27T12:01:00.000Z"};expect(await reopened.compareAndSetGhExecution(queued!.updatedAt,completed)).toMatchObject({kind:"accepted"});expect(await (await fixture.reopen()).getGhExecution(DEFAULT_ROOM_ID,command.submissionId)).toMatchObject({status:"completed",renderedText:"GitHub PR #98 — bounded"});}finally{fixture.close();}});

  it("atomically accepts submission, pointer, attempt, and audit or leaves no partial records",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-contract-"));temporaryDirectories.push(root);const fixture=await makeFixture(root);try{const createdAt="2026-08-27T12:00:00.000Z";const command={...submission(),command:"task" as const,invocation:{command:"task" as const,prompt:"ship",selection:{kind:"round-robin" as const}}};const audit={auditId:"atomic-audit",roomId:DEFAULT_ROOM_ID,submissionId:command.submissionId,command:"task" as const,invokerKind:"human" as const,invokerId:"human-1",targetAgentIds:["codex-sol" as const],createdAt};const attempt={attemptId:"atomic-attempt",roomId:DEFAULT_ROOM_ID,submissionId:command.submissionId,attempt:1,agentId:"codex-sol" as const,generationId:null,status:"queued" as const,reason:null,createdAt,updatedAt:createdAt};const acceptance={submission:command,audit,attempt,roundRobin:{expectedRevision:0,state:{roomId:DEFAULT_ROOM_ID,lastAssignedAgentId:"codex-sol" as const,revision:1,updatedAt:createdAt}}};expect(await fixture.repository.acceptCommand(acceptance)).toMatchObject({kind:"accepted"});expect(await fixture.repository.acceptCommand(acceptance)).toMatchObject({kind:"duplicate"});const reopened=await fixture.reopen();expect(await reopened.getCommandSubmission(DEFAULT_ROOM_ID,command.submissionId)).toEqual(command);expect(await reopened.getCommandAuditIdentity(DEFAULT_ROOM_ID,command.submissionId)).toEqual(audit);expect(await reopened.listCommandAttempts(DEFAULT_ROOM_ID,command.submissionId)).toEqual([attempt]);expect(await reopened.getRoundRobinState(DEFAULT_ROOM_ID)).toMatchObject({revision:1,lastAssignedAgentId:"codex-sol"});const conflicting={...command,submissionId:"conflicting",clientSubmissionId:"conflicting-client"};const rejected={...acceptance,submission:conflicting,audit:{...audit,auditId:"conflicting-audit",submissionId:"conflicting"},attempt:{...attempt,attemptId:"conflicting-attempt",submissionId:"conflicting"}};expect(await reopened.acceptCommand(rejected)).toMatchObject({kind:"conflict",actualRevision:1});expect(await reopened.getCommandSubmission(DEFAULT_ROOM_ID,"conflicting")).toBeUndefined();expect(await reopened.getCommandAuditIdentity(DEFAULT_ROOM_ID,"conflicting")).toBeUndefined();expect(await reopened.listCommandAttempts(DEFAULT_ROOM_ID,"conflicting")).toEqual([]);}finally{fixture.close();}});

  it("atomically supersedes ownership, advances the pointer, and creates the replacement",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-contract-"));temporaryDirectories.push(root);const fixture=await makeFixture(root);try{const createdAt="2026-08-27T12:00:00.000Z";const command={...submission(),command:"task" as const,invocation:{command:"task" as const,prompt:"ship",selection:{kind:"round-robin" as const}}};const audit={auditId:"reassign-audit",roomId:DEFAULT_ROOM_ID,submissionId:command.submissionId,command:"task" as const,invokerKind:"human" as const,invokerId:"human-1",targetAgentIds:["codex-sol" as const],createdAt};const attempt={attemptId:"attempt-one",roomId:DEFAULT_ROOM_ID,submissionId:command.submissionId,attempt:1,agentId:"codex-sol" as const,generationId:null,status:"queued" as const,reason:null,createdAt,updatedAt:createdAt};await fixture.repository.acceptCommand({submission:command,audit,attempt,roundRobin:{expectedRevision:0,state:{roomId:DEFAULT_ROOM_ID,lastAssignedAgentId:"codex-sol",revision:1,updatedAt:createdAt}}});const current={...attempt,status:"superseded" as const,reason:"launch stalled",updatedAt:"2026-08-27T12:01:00.000Z"};const next={...attempt,attemptId:"attempt-two",attempt:2,agentId:"claude-sonnet" as const,createdAt:current.updatedAt,updatedAt:current.updatedAt};expect(await fixture.repository.reassignCommandAttempt({expectedUpdatedAt:attempt.updatedAt,current,next,roundRobin:{expectedRevision:1,state:{roomId:DEFAULT_ROOM_ID,lastAssignedAgentId:"claude-sonnet",revision:2,updatedAt:current.updatedAt}}})).toMatchObject({kind:"accepted"});const reopened=await fixture.reopen();expect((await reopened.listCommandAttempts(DEFAULT_ROOM_ID,command.submissionId)).map(({status,agentId})=>({status,agentId}))).toEqual([{status:"superseded",agentId:"codex-sol"},{status:"queued",agentId:"claude-sonnet"}]);expect(await reopened.getRoundRobinState(DEFAULT_ROOM_ID)).toMatchObject({revision:2,lastAssignedAgentId:"claude-sonnet"});}finally{fixture.close();}});

  it("persists room-scoped records across restart and deduplicates submissions", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "amfaa-command-contract-")); temporaryDirectories.push(root); const fixture = await makeFixture(root);
    try {
      expect((await fixture.repository.createCommandSubmission(submission())).kind).toBe("created");
      expect((await fixture.repository.createCommandSubmission({ ...submission(), submissionId: "replayed" })).kind).toBe("duplicate");
      expect(await fixture.repository.getCommandSubmission("other-room", "submission-1")).toBeUndefined();
      expect(await fixture.repository.compareAndSetRoundRobinState(0, { roomId: DEFAULT_ROOM_ID, lastAssignedAgentId: "codex-sol", revision: 1, updatedAt: "2026-08-27T12:01:00.000Z" })).toMatchObject({ kind: "accepted" });
      const reopened = await fixture.reopen();
      expect(await reopened.getCommandSubmission(DEFAULT_ROOM_ID, "submission-1")).toMatchObject({ command: "poll" });
      expect(await reopened.getRoundRobinState(DEFAULT_ROOM_ID)).toMatchObject({ revision: 1, lastAssignedAgentId: "codex-sol" });
    } finally { fixture.close(); }
  });

  it("keeps polls authoritative and rejects duplicate or cross-room votes", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "amfaa-command-contract-")); temporaryDirectories.push(root); const fixture = await makeFixture(root);
    try {
      await fixture.repository.createCommandSubmission(submission());
      await fixture.repository.createCommandPoll({ pollId: "poll-1", roomId: DEFAULT_ROOM_ID, submissionId: "submission-1", question: "Choose", options: ["A", "B"], ...openPollLifecycle,createdAt: submission().createdAt });
      const vote = { roomId: DEFAULT_ROOM_ID, pollId: "poll-1", voterId: "human:human-1", mutationId:"vote-mutation-1", optionIndex: 1, createdAt: "2026-08-27T12:02:00.000Z" };
      expect((await fixture.repository.createCommandVote(vote)).kind).toBe("created");
      expect((await fixture.repository.createCommandVote({ ...vote, optionIndex: 0 })).kind).toBe("duplicate");
      expect((await fixture.repository.createCommandVote({ ...vote, voterId:"human:replacement-human" })).kind).toBe("duplicate");
      expect((await fixture.repository.createCommandVote({ ...vote, roomId: "other-room", voterId: "human:other" })).kind).toBe("rejected");
      expect(await fixture.repository.listCommandVotes(DEFAULT_ROOM_ID, "poll-1")).toEqual([vote]);
      expect(await fixture.repository.listCommandVotes("other-room", "poll-1")).toEqual([]);
      expect(JSON.stringify(fixture.repository.snapshot())).not.toMatch(/submission-1|poll-1|client-1/);
    } finally { fixture.close(); }
  });

  it("atomically bounds retained open polls under concurrent-abuse pressure", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "amfaa-command-contract-")); temporaryDirectories.push(root); const fixture = await makeFixture(root);
    try {
      for (let index = 0; index < MAX_OPEN_POLLS_PER_ROOM; index += 1) {
        const current = { ...submission(), submissionId: `cap-submission-${index}`, clientSubmissionId: `cap-client-${index}` };
        const poll = { pollId: `cap-poll-${index}`, roomId: DEFAULT_ROOM_ID, submissionId: current.submissionId, question: `Question ${index}`, options: ["A", "B"] as const, ...openPollLifecycle, createdAt: current.createdAt };
        const audit = { auditId: `cap-audit-${index}`, roomId: DEFAULT_ROOM_ID, submissionId: current.submissionId, command: "poll" as const, invokerKind: "human" as const, invokerId: "human-1", targetAgentIds: [] as const, createdAt: current.createdAt };
        expect(await fixture.repository.acceptCommand({ submission: current, poll, audit })).toMatchObject({ kind: "accepted" });
      }
      const overflow = { ...submission(), submissionId: "cap-submission-overflow", clientSubmissionId: "cap-client-overflow" };
      const overflowPoll = { pollId: "cap-poll-overflow", roomId: DEFAULT_ROOM_ID, submissionId: overflow.submissionId, question: "Overflow", options: ["A", "B"] as const, ...openPollLifecycle, createdAt: overflow.createdAt };
      const overflowAudit = { auditId: "cap-audit-overflow", roomId: DEFAULT_ROOM_ID, submissionId: overflow.submissionId, command: "poll" as const, invokerKind: "human" as const, invokerId: "human-1", targetAgentIds: [] as const, createdAt: overflow.createdAt };
      expect(await fixture.repository.acceptCommand({ submission: overflow, poll: overflowPoll, audit: overflowAudit })).toMatchObject({ kind: "rejected" });
      expect(await fixture.repository.getCommandSubmission(DEFAULT_ROOM_ID, overflow.submissionId)).toBeUndefined();
      expect(await fixture.repository.getCommandPoll(DEFAULT_ROOM_ID, overflowPoll.pollId)).toBeUndefined();
    } finally { fixture.close(); }
  });

  it("atomically closes polls, freezes one tally, and preserves idempotency across restart",async()=>{
    const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-contract-"));temporaryDirectories.push(root);const fixture=await makeFixture(root);
    try{
      const value=submission();const poll={pollId:"poll-close",roomId:DEFAULT_ROOM_ID,submissionId:value.submissionId,question:"Choose",options:["A","B"] as const,...openPollLifecycle,createdAt:value.createdAt};
      const audit={auditId:"poll-close-audit",roomId:DEFAULT_ROOM_ID,submissionId:value.submissionId,command:"poll" as const,invokerKind:"human" as const,invokerId:"human-1",targetAgentIds:[] as const,createdAt:value.createdAt};
      await fixture.repository.acceptCommand({submission:value,poll,audit});
      const vote={roomId:DEFAULT_ROOM_ID,pollId:poll.pollId,voterId:"human:one",mutationId:"vote-before-close",optionIndex:1,createdAt:"2026-08-27T12:01:00.000Z"};
      expect(await fixture.repository.createCommandVote(vote)).toMatchObject({kind:"created"});
      const close={roomId:DEFAULT_ROOM_ID,pollId:poll.pollId,expectedRevision:1,mutationId:"close-mutation-one",closerKind:"human" as const,closerId:"human-1",closedAt:"2026-08-27T12:02:00.000Z"};
      expect(await fixture.repository.closeCommandPoll(close)).toMatchObject({kind:"closed",poll:{state:"CLOSED",revision:2,finalTallies:[0,1],finalTotalVotes:1}});
      expect(await fixture.repository.closeCommandPoll(close)).toMatchObject({kind:"duplicate",poll:{revision:2}});
      expect(await fixture.repository.createCommandVote(vote)).toMatchObject({kind:"duplicate"});
      expect(await fixture.repository.createCommandVote({...vote,voterId:"human:late",mutationId:"vote-after-close"})).toMatchObject({kind:"rejected"});
      const reopened=await fixture.reopen();expect(await reopened.getCommandPoll(DEFAULT_ROOM_ID,poll.pollId)).toMatchObject({state:"CLOSED",revision:2,closeMutationId:"close-mutation-one",finalTallies:[0,1]});
    }finally{fixture.close();}
  });

  it("atomically accepts a poll with its audit identity",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-contract-"));temporaryDirectories.push(root);const fixture=await makeFixture(root);try{const value=submission();const poll={pollId:"poll-atomic",roomId:DEFAULT_ROOM_ID,submissionId:value.submissionId,question:"Choose",options:["A","B"] as const,...openPollLifecycle,createdAt:value.createdAt};const audit={auditId:"poll-audit",roomId:DEFAULT_ROOM_ID,submissionId:value.submissionId,command:"poll" as const,invokerKind:"human" as const,invokerId:"human-1",targetAgentIds:[] as const,createdAt:value.createdAt};expect(await fixture.repository.acceptCommand({submission:value,poll,audit})).toMatchObject({kind:"accepted"});const reopened=await fixture.reopen();expect(await reopened.getCommandPoll(DEFAULT_ROOM_ID,poll.pollId)).toEqual(poll);expect(await reopened.getCommandAuditIdentity(DEFAULT_ROOM_ID,value.submissionId)).toEqual(audit);}finally{fixture.close();}});

  it("persists per-target POV progress and keeps concurrent SQLite acceptance transactional",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-contract-"));temporaryDirectories.push(root);const fixture=await makeFixture(root);try{const value={...submission(),command:"pov" as const,invocation:{command:"pov" as const,prompt:"Discuss",selection:{kind:"all-eligible" as const}}};const audit={auditId:"pov-audit",roomId:DEFAULT_ROOM_ID,submissionId:value.submissionId,command:"pov" as const,invokerKind:"human" as const,invokerId:"human-1",targetAgentIds:["codex-sol" as const,"claude-sonnet" as const],createdAt:value.createdAt};const pov={executionId:"pov-execution",roomId:DEFAULT_ROOM_ID,submissionId:value.submissionId,targetAgentIds:audit.targetAgentIds,processedTargetAgentIds:[] as ActiveAgentId[],status:"queued" as const,reason:null,createdAt:value.createdAt,updatedAt:value.createdAt};expect(await fixture.repository.acceptCommand({submission:value,audit,povExecution:pov})).toMatchObject({kind:"accepted"});const active={...pov,status:"active" as const,currentTargetAgentId:"codex-sol" as const,generationId:"pov-generation",deliveryMessages:["durable view"],deliveryResult:{sessionId:"pov-session",permission:"writable" as const},updatedAt:"2026-08-27T12:01:00.000Z"};expect(await fixture.repository.compareAndSetPovExecution(pov.updatedAt,active)).toMatchObject({kind:"accepted"});const reopened=await fixture.reopen();expect(await reopened.getPovExecution(DEFAULT_ROOM_ID,value.submissionId)).toEqual(active);
      if(_backend==="SQLite"){const make=(index:number)=>{const submissionValue={...submission(),submissionId:`concurrent-${index}`,clientSubmissionId:`concurrent-client-${index}`,command:"task" as const,invocation:{command:"task" as const,prompt:"work",selection:{kind:"round-robin" as const}}};return{submission:submissionValue,audit:{...audit,auditId:`concurrent-audit-${index}`,submissionId:submissionValue.submissionId,command:"task" as const,targetAgentIds:["codex-sol" as const]},attempt:{attemptId:`concurrent-attempt-${index}`,roomId:DEFAULT_ROOM_ID,submissionId:submissionValue.submissionId,attempt:1,agentId:"codex-sol" as const,generationId:null,status:"queued" as const,reason:null,createdAt:submissionValue.createdAt,updatedAt:submissionValue.createdAt},roundRobin:{expectedRevision:0,state:{roomId:DEFAULT_ROOM_ID,lastAssignedAgentId:"codex-sol" as const,revision:1,updatedAt:submissionValue.createdAt}}};};const settled=await Promise.allSettled([reopened.acceptCommand(make(1)),reopened.acceptCommand(make(2))]);expect(settled.every((result)=>result.status==="fulfilled")).toBe(true);}
    }finally{fixture.close();}});

  it("persists attempts, audit identities, and bounded private diagnostics idempotently", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "amfaa-command-contract-")); temporaryDirectories.push(root); const fixture = await makeFixture(root);
    try {
      await fixture.repository.createCommandSubmission(submission());
      const attempt = { attemptId: "attempt-1", roomId: DEFAULT_ROOM_ID, submissionId: "submission-1", attempt: 1, agentId: "codex-sol" as const, generationId: "generation-1", status: "active" as const, reason: null, createdAt: submission().createdAt, updatedAt: submission().createdAt };
      expect((await fixture.repository.createCommandAttempt(attempt)).kind).toBe("created");
      expect((await fixture.repository.createCommandAttempt(attempt)).kind).toBe("duplicate");
      const deliveryPending = { ...attempt, status: "delivery-pending" as const, deliveryMessages: ["durable result"], deliveryResult: { sessionId: "session-1", permission: "writable" as const, codeEpoch: "epoch-1", cursorMessageId: "message-1" }, updatedAt: "2026-08-27T12:02:00.000Z" };
      expect(await fixture.repository.compareAndSetCommandAttempt(attempt.updatedAt, deliveryPending)).toMatchObject({ kind: "accepted" });
      expect((await fixture.repository.listPendingCommandAttempts(DEFAULT_ROOM_ID))[0]).toEqual(deliveryPending);
      const completed = { ...deliveryPending, status: "completed" as const, updatedAt: "2026-08-27T12:03:00.000Z" };
      expect(await fixture.repository.compareAndSetCommandAttempt(deliveryPending.updatedAt, completed)).toMatchObject({ kind: "accepted" });
      expect(await fixture.repository.compareAndSetCommandAttempt(attempt.updatedAt, { ...completed, status: "failed" })).toEqual({ kind: "conflict" });
      expect(await fixture.repository.listPendingCommandAttempts(DEFAULT_ROOM_ID)).toEqual([]);
      const audit = { auditId: "audit-1", roomId: DEFAULT_ROOM_ID, submissionId: "submission-1", command: "poll" as const, invokerKind: "human" as const, invokerId: "human-1", targetAgentIds: [] as const, createdAt: submission().createdAt };
      expect((await fixture.repository.createCommandAuditIdentity(audit)).kind).toBe("created");
      const diagnostic = { recordId: "diagnostic-1", roomId: DEFAULT_ROOM_ID, agentId: "codex-sol" as const, attemptId: "attempt-1", generationId: "generation-1", correlationId: "correlation-1", promptHead: "bounded", promptFingerprint: "sha256:prompt", reason: "stalled", metadata: { bytes: 7 }, diagnosticText: "safe partial", createdAt: submission().createdAt };
      expect((await fixture.repository.appendDiagnostic(diagnostic)).kind).toBe("created");
      expect((await fixture.repository.appendDiagnostic({ ...diagnostic, recordId: "replay" })).kind).toBe("duplicate");
      const reopened = await fixture.reopen();
      expect(await reopened.listCommandAttempts(DEFAULT_ROOM_ID, "submission-1")).toEqual([completed]);
      expect(await reopened.getCommandAuditIdentity(DEFAULT_ROOM_ID, "submission-1")).toEqual(audit);
      expect(await reopened.listDiagnostics(DEFAULT_ROOM_ID, "codex-sol")).toEqual([diagnostic]);
      expect(await reopened.getDiagnostic(DEFAULT_ROOM_ID, "codex-sol", "diagnostic-1")).toEqual(diagnostic);
      expect(await reopened.listDiagnostics(DEFAULT_ROOM_ID, { agentId: "codex-sol", search: "SAFE PARTIAL", reason: "stalled" })).toEqual([diagnostic]);
      expect(await reopened.listDiagnostics(DEFAULT_ROOM_ID, { agentId: "codex-sol", search: "%" })).toEqual([]);
      expect(await reopened.listDiagnostics(DEFAULT_ROOM_ID, { agentId: "codex-sol", search: "_" })).toEqual([]);
      expect(await reopened.listDiagnostics("other-room", "codex-sol")).toEqual([]);
    } finally { fixture.close(); }
  });

  it("compacts expired command families into replay tombstones and paginates recent polls",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-contract-"));temporaryDirectories.push(root);const fixture=await makeFixture(root);try{const old={...submission(),createdAt:"2020-01-01T00:00:00.000Z"};const oldPoll={pollId:"poll-old",roomId:DEFAULT_ROOM_ID,submissionId:old.submissionId,question:"Old",options:["A","B"] as const,...openPollLifecycle,createdAt:old.createdAt};const oldAudit={auditId:"audit-old",roomId:DEFAULT_ROOM_ID,submissionId:old.submissionId,command:"poll" as const,invokerKind:"human" as const,invokerId:"human-1",targetAgentIds:[] as const,createdAt:old.createdAt};expect(await fixture.repository.acceptCommand({submission:old,poll:oldPoll,audit:oldAudit})).toMatchObject({kind:"accepted"});expect(await fixture.repository.closeCommandPoll({roomId:DEFAULT_ROOM_ID,pollId:oldPoll.pollId,expectedRevision:1,mutationId:"old-poll-close",closerKind:"human",closerId:"human-1",closedAt:"2020-01-02T00:00:00.000Z"})).toMatchObject({kind:"closed"});await fixture.repository.compactCommandRecords(DEFAULT_ROOM_ID,"2026-08-27T12:00:00.000Z");expect(await fixture.repository.getCommandSubmission(DEFAULT_ROOM_ID,old.submissionId)).toBeUndefined();expect(await fixture.repository.getCommandPoll(DEFAULT_ROOM_ID,oldPoll.pollId)).toBeUndefined();expect(await fixture.repository.acceptCommand({submission:old,poll:oldPoll,audit:oldAudit})).toMatchObject({kind:"compacted-duplicate",tombstone:{clientSubmissionId:old.clientSubmissionId}});
      for(let index=0;index<3;index++){const createdAt="2026-08-27T12:02:00.000Z";const value={...submission(),submissionId:`recent-${index}`,clientSubmissionId:`recent-client-${index}`,createdAt};const poll={pollId:`recent-poll-${index}`,roomId:DEFAULT_ROOM_ID,submissionId:value.submissionId,question:`Recent ${index}`,options:["A","B"] as const,...openPollLifecycle,createdAt};const audit={...oldAudit,auditId:`recent-audit-${index}`,submissionId:value.submissionId,createdAt};expect(await fixture.repository.acceptCommand({submission:value,poll,audit})).toMatchObject({kind:"accepted"});}const first=await fixture.repository.listCommandPolls(DEFAULT_ROOM_ID,{limit:2});expect(first.map((item)=>item.pollId)).toEqual(["recent-poll-2","recent-poll-1"]);expect((await fixture.repository.listCommandPolls(DEFAULT_ROOM_ID,{limit:2,before:commandPollCursor(first[1]!)})).map((item)=>item.pollId)).toEqual(["recent-poll-0"]);expect(await fixture.repository.closeCommandPoll({roomId:DEFAULT_ROOM_ID,pollId:"recent-poll-2",expectedRevision:1,mutationId:"recent-poll-close-2",closerKind:"human",closerId:"human-1",closedAt:"2026-08-27T12:03:00.000Z"})).toMatchObject({kind:"closed"});expect((await fixture.repository.listCommandPolls(DEFAULT_ROOM_ID,{limit:2,state:"OPEN"})).map((item)=>item.pollId)).toEqual(["recent-poll-1","recent-poll-0"]);
    }finally{fixture.close();}});

  it("keeps another room's matching command identifiers during JSON compaction",async()=>{if(_backend!=="JSON")return;const root=await mkdtemp(path.join(os.tmpdir(),"amfaa-command-contract-"));temporaryDirectories.push(root);const fixture=await makeFixture(root);try{const old={...submission(),submissionId:"shared-submission",clientSubmissionId:"default-client",createdAt:"2020-01-01T00:00:00.000Z"};const other={...old,roomId:"other-room",clientSubmissionId:"other-client"};await fixture.repository.createCommandSubmission(old);await fixture.repository.createCommandPoll({pollId:"shared-poll",roomId:DEFAULT_ROOM_ID,submissionId:old.submissionId,question:"Default",options:["A","B"],...openPollLifecycle,createdAt:old.createdAt});await fixture.repository.createCommandSubmission(other);await fixture.repository.createCommandPoll({pollId:"shared-poll",roomId:"other-room",submissionId:other.submissionId,question:"Other",options:["A","B"],...openPollLifecycle,createdAt:other.createdAt});await fixture.repository.createCommandVote({roomId:"other-room",pollId:"shared-poll",voterId:"other-voter",mutationId:"other-vote",optionIndex:1,createdAt:other.createdAt});await fixture.repository.compactCommandRecords(DEFAULT_ROOM_ID,"2026-08-27T12:00:00.000Z");expect(await fixture.repository.getCommandSubmission("other-room","shared-submission")).toEqual(other);expect(await fixture.repository.getCommandPoll("other-room","shared-poll")).toMatchObject({question:"Other"});expect(await fixture.repository.listCommandVotes("other-room","shared-poll")).toHaveLength(1);}finally{fixture.close();}});
});
