import { isActiveAgentId } from "../../shared/participants.js";
import { ROOM_COMMANDS } from "../../shared/command-domain.js";
import { MAX_DIAGNOSTIC_PROMPT_HEAD, MAX_DIAGNOSTIC_TEXT, type CommandAcceptance, type CommandAttempt, type CommandAuditIdentity, type CommandPoll, type CommandPovExecution, type CommandReassignment, type CommandSubmission, type CommandTombstone, type CommandVote, type DiagnosticRecord, type RoundRobinState } from "../command-record.js";

export interface JsonCommandState { readonly schemaVersion: 1; readonly submissions: readonly CommandSubmission[]; readonly tombstones:readonly CommandTombstone[]; readonly roundRobin: readonly RoundRobinState[]; readonly attempts: readonly CommandAttempt[]; readonly povExecutions: readonly CommandPovExecution[]; readonly polls: readonly CommandPoll[]; readonly votes: readonly CommandVote[]; readonly audits: readonly CommandAuditIdentity[]; readonly diagnostics: readonly DiagnosticRecord[] }
export function emptyJsonCommandState(): JsonCommandState { return { schemaVersion: 1, submissions: [], tombstones:[], roundRobin: [], attempts: [], povExecutions: [], polls: [], votes: [], audits: [], diagnostics: [] }; }
const string = (value: unknown, max = 500) => typeof value === "string" && value.length > 0 && value.length <= max;
export function validSubmission(value: CommandSubmission) { return string(value?.submissionId) && string(value.roomId) && string(value.clientSubmissionId) && ROOM_COMMANDS.includes(value.command) && value.invocation?.command === value.command && string(value.invoker?.id) && string(value.invoker?.displayName) && (value.invoker?.kind === "human" || value.invoker?.kind === "agent") && string(value.createdAt); }
export function validRoundRobin(value: RoundRobinState) { return string(value?.roomId) && (value.lastAssignedAgentId === null || isActiveAgentId(value.lastAssignedAgentId)) && Number.isSafeInteger(value.revision) && value.revision >= 0 && string(value.updatedAt); }
export function validAttempt(value: CommandAttempt) { const deliveryValid=value?.status!=="delivery-pending"||Array.isArray(value.deliveryMessages)&&value.deliveryMessages.length>0&&value.deliveryMessages.length<=3&&value.deliveryMessages.every((message)=>string(message,4_000));return string(value?.attemptId) && string(value.roomId) && string(value.submissionId) && Number.isSafeInteger(value.attempt) && value.attempt > 0 && isActiveAgentId(value.agentId) && ["queued", "active", "delivery-pending", "completed", "failed", "superseded"].includes(value.status) && deliveryValid && string(value.createdAt) && string(value.updatedAt); }
export function validPoll(value: CommandPoll) { return string(value?.pollId) && string(value.roomId) && string(value.submissionId) && string(value.question) && Array.isArray(value.options) && value.options.length >= 2 && value.options.length <= 12 && value.options.every((option) => string(option)) && string(value.createdAt); }
export function validVote(value: CommandVote) { return string(value?.roomId) && string(value.pollId) && string(value.voterId) && string(value.mutationId,100) && Number.isSafeInteger(value.optionIndex) && value.optionIndex >= 0 && string(value.createdAt); }
export function validAudit(value: CommandAuditIdentity) { return string(value?.auditId) && string(value.roomId) && string(value.submissionId) && ROOM_COMMANDS.includes(value.command) && (value.invokerKind === "human" || value.invokerKind === "agent") && string(value.invokerId) && Array.isArray(value.targetAgentIds) && value.targetAgentIds.every(isActiveAgentId); }
export function validPovExecution(value: CommandPovExecution) { return string(value?.executionId) && string(value.roomId) && string(value.submissionId) && Array.isArray(value.targetAgentIds) && value.targetAgentIds.length > 0 && value.targetAgentIds.every(isActiveAgentId) && ["queued","active","completed","failed","cancelled"].includes(value.status) && string(value.createdAt) && string(value.updatedAt); }
export function validTombstone(value:CommandTombstone){return string(value?.roomId)&&string(value.submissionId)&&string(value.clientSubmissionId)&&ROOM_COMMANDS.includes(value.command)&&string(value.compactedAt);}
export function validDiagnostic(value: DiagnosticRecord) { return string(value?.recordId) && string(value.roomId) && isActiveAgentId(value.agentId) && string(value.attemptId) && string(value.correlationId) && string(value.promptFingerprint) && string(value.reason) && (value.promptHead === null || value.promptHead.length <= MAX_DIAGNOSTIC_PROMPT_HEAD) && (value.diagnosticText === null || value.diagnosticText.length <= MAX_DIAGNOSTIC_TEXT) && string(value.createdAt); }
export function validCommandAcceptance(value: CommandAcceptance) { const {submission,audit,poll,attempt,povExecution,roundRobin}=value||{} as CommandAcceptance; return validSubmission(submission)&&validAudit(audit)&&audit.roomId===submission.roomId&&audit.submissionId===submission.submissionId&&audit.command===submission.command&&(!poll||validPoll(poll)&&poll.roomId===submission.roomId&&poll.submissionId===submission.submissionId&&submission.command==="poll")&&(!attempt||validAttempt(attempt)&&attempt.roomId===submission.roomId&&attempt.submissionId===submission.submissionId&&submission.command==="task"&&attempt.attempt===1&&attempt.status==="queued")&&(!povExecution||validPovExecution(povExecution)&&povExecution.roomId===submission.roomId&&povExecution.submissionId===submission.submissionId&&submission.command==="pov"&&povExecution.status==="queued")&&(!roundRobin||validRoundRobin(roundRobin.state)&&roundRobin.state.roomId===submission.roomId&&roundRobin.state.revision===roundRobin.expectedRevision+1&&submission.command==="task"); }
export function validCommandReassignment(value:CommandReassignment){const{current,next,roundRobin}=value||{} as CommandReassignment;return validAttempt(current)&&validAttempt(next)&&current.status==="superseded"&&next.status==="queued"&&current.roomId===next.roomId&&current.submissionId===next.submissionId&&next.attempt===current.attempt+1&&Boolean(roundRobin)&&roundRobin.expectedRevision+1===roundRobin.state.revision&&roundRobin.state.roomId===current.roomId&&validRoundRobin(roundRobin.state)&&value.expectedUpdatedAt!==current.updatedAt;}
export function normalizeJsonCommandState(input: unknown): JsonCommandState {
  if (!input || typeof input !== "object") return emptyJsonCommandState();
  const value = input as Partial<JsonCommandState>;
  const take = <T>(candidate: unknown, validate: (entry: T) => boolean): T[] => Array.isArray(candidate) ? candidate.filter((entry): entry is T => validate(entry as T)) : [];
  return { schemaVersion: 1, submissions: take(value.submissions, validSubmission), tombstones:take(value.tombstones,validTombstone), roundRobin: take(value.roundRobin, validRoundRobin), attempts: take(value.attempts, validAttempt), povExecutions: take(value.povExecutions, validPovExecution), polls: take(value.polls, validPoll), votes: take(value.votes, validVote), audits: take(value.audits, validAudit), diagnostics: take(value.diagnostics, validDiagnostic) };
}
