import { isActiveAgentId } from "../../shared/participants.js";
import { ROOM_COMMANDS } from "../../shared/command-domain.js";
import { MAX_DIAGNOSTIC_PROMPT_HEAD, MAX_DIAGNOSTIC_TEXT, type CommandAttempt, type CommandAuditIdentity, type CommandPoll, type CommandSubmission, type CommandVote, type DiagnosticRecord, type RoundRobinState } from "../command-record.js";

export interface JsonCommandState { readonly schemaVersion: 1; readonly submissions: readonly CommandSubmission[]; readonly roundRobin: readonly RoundRobinState[]; readonly attempts: readonly CommandAttempt[]; readonly polls: readonly CommandPoll[]; readonly votes: readonly CommandVote[]; readonly audits: readonly CommandAuditIdentity[]; readonly diagnostics: readonly DiagnosticRecord[] }
export function emptyJsonCommandState(): JsonCommandState { return { schemaVersion: 1, submissions: [], roundRobin: [], attempts: [], polls: [], votes: [], audits: [], diagnostics: [] }; }
const string = (value: unknown, max = 500) => typeof value === "string" && value.length > 0 && value.length <= max;
export function validSubmission(value: CommandSubmission) { return string(value?.submissionId) && string(value.roomId) && string(value.clientSubmissionId) && ROOM_COMMANDS.includes(value.command) && value.invocation?.command === value.command && string(value.invoker?.id) && (value.invoker?.kind === "human" || value.invoker?.kind === "agent") && string(value.createdAt); }
export function validRoundRobin(value: RoundRobinState) { return string(value?.roomId) && (value.lastAssignedAgentId === null || isActiveAgentId(value.lastAssignedAgentId)) && Number.isSafeInteger(value.revision) && value.revision >= 0 && string(value.updatedAt); }
export function validAttempt(value: CommandAttempt) { return string(value?.attemptId) && string(value.roomId) && string(value.submissionId) && Number.isSafeInteger(value.attempt) && value.attempt > 0 && isActiveAgentId(value.agentId) && ["queued", "active", "completed", "failed", "superseded"].includes(value.status) && string(value.createdAt) && string(value.updatedAt); }
export function validPoll(value: CommandPoll) { return string(value?.pollId) && string(value.roomId) && string(value.submissionId) && string(value.question) && Array.isArray(value.options) && value.options.length >= 2 && value.options.length <= 12 && value.options.every((option) => string(option)); }
export function validVote(value: CommandVote) { return string(value?.roomId) && string(value.pollId) && string(value.voterId) && Number.isSafeInteger(value.optionIndex) && value.optionIndex >= 0 && string(value.createdAt); }
export function validAudit(value: CommandAuditIdentity) { return string(value?.auditId) && string(value.roomId) && string(value.submissionId) && ROOM_COMMANDS.includes(value.command) && (value.invokerKind === "human" || value.invokerKind === "agent") && string(value.invokerId) && Array.isArray(value.targetAgentIds) && value.targetAgentIds.every(isActiveAgentId); }
export function validDiagnostic(value: DiagnosticRecord) { return string(value?.recordId) && string(value.roomId) && isActiveAgentId(value.agentId) && string(value.attemptId) && string(value.correlationId) && string(value.promptFingerprint) && string(value.reason) && (value.promptHead === null || value.promptHead.length <= MAX_DIAGNOSTIC_PROMPT_HEAD) && (value.diagnosticText === null || value.diagnosticText.length <= MAX_DIAGNOSTIC_TEXT) && string(value.createdAt); }
export function normalizeJsonCommandState(input: unknown): JsonCommandState {
  if (!input || typeof input !== "object") return emptyJsonCommandState();
  const value = input as Partial<JsonCommandState>;
  const take = <T>(candidate: unknown, validate: (entry: T) => boolean): T[] => Array.isArray(candidate) ? candidate.filter((entry): entry is T => validate(entry as T)) : [];
  return { schemaVersion: 1, submissions: take(value.submissions, validSubmission), roundRobin: take(value.roundRobin, validRoundRobin), attempts: take(value.attempts, validAttempt), polls: take(value.polls, validPoll), votes: take(value.votes, validVote), audits: take(value.audits, validAudit), diagnostics: take(value.diagnostics, validDiagnostic) };
}
